bika/lims/utils/__init__.py
Without this fix the content-type gets set to "application/application/pdf" which will cause problems on some mail servers.
=> Update content type of PDF's

CHANGELOG.txt, bika/lims/browser/js/bika.lims.analysisrequest.add.js, bika/lims/browser/js/bika.lims.loader.js, bika/lims/browser/widgets/referencewidget.py, bika/lims/exportimport/setupdata/__init__.py, bika/lims/skins/bika/bika_widgets/referencewidget.js, bika/lims/skins/bika/bika_widgets/referencewidget.pt, bika/lims/skins/bika/ploneCustom.css.dtml
**This other PR should be reviewed and accepted or rejected at the same time**: http://git.io/tb3cjQ
**Basic usage**
```python
ExtReferenceField(
'Doctor',
widget=ReferenceWidget(
add_button={
'visible': True,
'url': 'doctors/portal_factory/Doctor/new/edit',
'return_fields': ['Firstname', 'Surname'],
}
),
),
```
url: the url to be loaded inside the overlay
return_fields: the fields to be used to fill the referencewidget after the submit
**Advanced usage**
```python
ExtReferenceField(
'Patient',
widget=ReferenceWidget(
add_button={
'visible': True,
'url': 'patients/portal_factory/Patient/new/edit',
'return_fields': ['Firstname', 'Surname'],
'js_controllers': ['#patient-base-edit',],
'overlay_handler': 'HealthPatientOverlayHandler',
}
),
),
```
js_controllers: the controllers we need to …
=> Issue/lims 1536 Add buttons for reference widgets dynamically

bika/lims/browser/analysisrequest/manage_analyses.py
...ing a sample with Sampling Workflow enabled
Preventive try-catch: When you change the keyword from an Analysis Specification, the ResultsRange doesn't change the keyword value. This generates an error while broswer/analysisrequest/getResultsRange() is searching AS' UID with the keyword.
https://jira.bikalabs.com/browse/LIMS-1614
http://sentry.bikalabs.com/bikalims/dev-demo-test/group/4920/
=> Issue/1614  Error when selecting Analysis Administration Tab after receiving a sample with Sampling Workflow enabled

bika/lims/browser/fields/aranalysesfield.py
One of my test sites is called 'asdf'.  Then, I made a service with
keyword 'asdf'.  Suddenly this code thought that my site object was
a service, since 'asdf' is an attribute of the root.
=> shashattr instead of hasattr - avoid acquisition.

bika/lims/browser/clientfolder.py, bika/lims/skins/bika/logged_in.cpy
Before upgrade, this key will not exist, and login will "fail"
until migration has happened.
@zylinx fyi.
=> defend against nonexistent landing_page in registry

bika/lims/skins/bika/guard_retract_transition.py
- This error arose when upgrading bika from 3.1.6 to 3.1.7 and then trying to view all the Analysis Requests.
=> Adding a fix for the "ImportError: cannot import name Retract".

buildout.cfg
Running bin/buildout gives error when installing robot. Traceback: http://pastie.org/10060732 . This is fixed by splitting 'eggs' in [robot] section into three lines, separating 'eggs', 'buildout:eggs' and 'robotframework'.
The fix is manually tested to work with virtualenv in Ubuntu 14.04. 'bin/buildout ran without previously mentioned errors.
=> Fix error when running bin/buildout

bika/lims/content/pricelist.py
If a lab product had no unit and volume, creating a pricelist for lab products gave an error that 'print_detail' was not referenced. This was fixed by initializing print_detail and shifting a case accordingly.
The modified version had been manually tested and creating pricelist of lab products with and without volume and unit was successful.
=> [LIMS-1737] Fixed error in adding pricelists

bika/lims/browser/reports/selection_macros/__init__.py, docs/CHANGELOG.txt
In reports, instead of start dates and end dates, '${start_date}' and '${end_date}' are being shown. This is because of a mistake in mapping.
The issue is fixed and is manually tested by generating report of received samples. The report now shows both start dates and end dates or any of them individually.
=> [LIMS-1724] Fixed dates on reports

bika/lims/content/analysis.py, docs/CHANGELOG.txt
Due to some code refactoring done for [LIMS-1729 Analysis Specification Not applying to Sample when Selected](https://jira.bikalabs.com/browse/LIMS-1729)
```
Module bika.lims.browser.analysisrequest.manage_results, line 49, in _call_
Module bika.lims.browser.bika_listing, line 786, in contents_table
Module bika.lims.browser.bika_listing, line 875, in _init_
Module bika.lims.browser.analyses, line 591, in folderitems
Module bika.lims.browser.analyses, line 139, in get_analysis_spec
Module bika.lims.content.analysis, line 321, in getResultsRange
AttributeError: 'NoneType' object has no attribute 'getResultsRangeDict'
```
=> LIMS-1738: Regression. 'NoneType' object has no attribute 'getResultsRangeDict'

bika/lims/content/labproduct.py, docs/CHANGELOG.txt
The error occurs because price field for product is not mandatory and a product with no price raises error when adding supply order.
After discussion with xispa, I have made the price of Products mandatory. Refer the related pull request [#1488](https://github.com/bikalabs/Bika-LIMS/pull/1488).
=> LIMS-1748 Fixed error in adding supply order

bika/lims/browser/templates/supplyorder_edit.pt, docs/CHANGELOG.txt
The unwanted overlay pops up because the form has `name="edit"`. I traced back where the overlay came from and it is `plone.app.discussion.javascript/comments.js`. It added prepOverlay to all forms with `name="edit"` for some unwanted reason.
Removing `name="edit"` not only fixed the issue, but also gave no other errors in the supply order workflow.
=> LIMS-1741 Fixed overlay when saving supply order

bika/lims/browser/analysisrequest/manage_analyses.py, bika/lims/browser/analysisrequest/publish.py, bika/lims/browser/analysisrequest/templates/analysisrequest_publish.pt, bika/lims/browser/analysisrequest/workflow.py, bika/lims/browser/js/bika.lims.analysisrequest.publish.js, bika/lims/browser/widgets/analysisprofileanalyseswidget.py, bika/lims/browser/widgets/artemplateanalyseswidget.py, bika/lims/content/analysisprofile.py, bika/lims/content/analysisrequest.py, bika/lims/content/analysisservice.py, bika/lims/content/artemplate.py, bika/lims/tests/test_hiddenanalyses.py, bika/lims/utils/analysisrequest.py, docs/CHANGELOG.txt
Added show/hide capabilities for Analyses:
- New checkbox field 'Hidden' in Analysis Service view
- New column in Analyses view from AR Profile. A checkbox field 'Hidden'
- New column in Analyses view from AR Template. A checkbox field 'Hidden'
- New column in Manage Analyses from AR View. A checkbox field 'Hidden'
- New option 'Show/Hide analyses' in reports
- By default, the 'hidden' analyses will not be displayed in results reports. 
- 'Hidden' field value overriding (if set in AR Profile, overrides the value set at AS level and so on).
```
jordi@darwin:~/dev/labsanmartin/bikalims/zinstance$ bin/test -s bika.lims -t TestHiddenAnalyses
Set up plone.testing.z2.Startup in …
```
=> LIMS-1324 Allow to hide analyses in results reports

bika/lims/browser/analyses.py, bika/lims/browser/analysisrequest/workflow.py, bika/lims/browser/js/bika.lims.worksheet.js, bika/lims/browser/worksheet.py, bika/lims/content/analysis.py, bika/lims/content/analysisservice.py, bika/lims/content/referenceanalysis.py, bika/lims/tests/test_limitdetections.py, docs/CHANGELOG.txt
- Lower and Upper Detection Limits fields in AS (LDL and UDL)
- "Allow manual Detection Limit" field in AS
- In manage_results, if an analysis has the manual detection limit set to true, allow the user/analyst to set a detection limit
- Results formatting with LDL and UDL
```
jordi@darwin:~/dev/labsanmartin/bikalims/zinstance$ bin/test -s bika.lims -t TestLimitDetections
Set up plone.testing.z2.Startup in 0.154 seconds.
Set up plone.app.testing.layers.PloneFixture in 5.113 seconds.
Set up bika.lims.testing.BikaTestLayer in 42.882 seconds.
Set up bika.lims.testing.BikaTestingLayer:Functional in 0.000 seconds.
Running:
Ran 1 tests with 0 failures and 0 errors in 1.832 …
```
=> LIMS-1700 Lower and Upper Detection Limits (LDL/UDL). Allow manual input

bika/lims/content/sample.py, docs/CHANGELOG.txt
`workflow_script_dispose` is missing in content/sample.py and adding this fixed the issue.
SamplingWorkflow robot tests ran with no failures. The warnings are because my chromedriver is unable to take screenshots.
```
Set up plone.testing.z2.Startup in 0.245 seconds.
Set up plone.app.testing.layers.PloneFixture in 8.325 seconds.
Set up bika.lims.testing.BikaTestLayer in 1 minutes 10.401 seconds.
Running:
1/5 (20.0%)[ WARN ] Keyword 'Capture Page Screenshot' could not be run on failure: WebDriverException: Message: u'no such session\n  (Driver info: …
```
=> LIMS-1474 Disposed date is not shown in SampleView

bika/lims/browser/analyses.py, bika/lims/browser/calcs.py, bika/lims/browser/js/bika.lims.utils.calcs.js, bika/lims/content/analysis.py, bika/lims/content/calculation.py, bika/lims/exportimport/setupdata/__init__.py, bika/lims/tests/test_calculations.py, bika/lims/validators.py, docs/CHANGELOG.txt
Accepted operands/wildcards in calculations:
- [INTERIMKEY]: (float) interim's value
- [ASKEY]: (float) analysis result
- [ASKEY.LDL]: (float) analysis' Low Detection Limit (default or manual)
- [ASKEY.UDL]: (float) analysis' Upper Detection Limit (default or manual)
- [ASKEY.BELOWLDL]: (bool) if the result is below LDL
- [ASKEY.ABOVEUDL]: (bool) if the result is above UDL
Some examples of formulas:
```
[AS1.LDL]+[AS2.LDL]+[INTERIM1]
'< LDL' if [AS2.BELOWLDL] else [AS2]*[AS1]
('> '+[AS2.UDL]) if [AS2.ABOVEUDL] else [AS2]+[INTERIM1]
[AS1] If ([AS2.BELOWLDL] or [AS2.ABOVEUDL]) else [AS2]
```
Functional tests:
```
$ bin/test -v -p -s bika.lims --suite-name='bika.lims.tests'
Set up …
```
=> LIMS-1769 Allow to use LDL and UDL in calculations

bika/lims/browser/analyses.py, bika/lims/browser/calcs.py, bika/lims/browser/js/bika.lims.analysisservice.js, bika/lims/browser/js/bika.lims.utils.calcs.js, bika/lims/browser/js/bika.lims.worksheet.js, bika/lims/content/analysis.py, bika/lims/content/analysisservice.py, bika/lims/content/calculation.py, bika/lims/exportimport/setupdata/__init__.py, bika/lims/skins/bika/ploneCustom.css.dtml, bika/lims/tests/test_calculations.py, bika/lims/tests/test_limitdetections.py, bika/lims/validators.py, docs/CHANGELOG.txt
**Requires PR https://github.com/bikalabs/Bika-LIMS/pull/1500 to be accepted first!!**
With [LIMS-1700](https://jira.bikalabs.com/browse/LIMS-1700), the analyst can input a detection limit manually if the Y/N field "Allow Manual Detection Limit" option is enabled in the 'Analysis Service' view. In some cases, the analyst must be able to set the default Detection Limit (LDL or UDL), but without being able to change it.
Add an additional Y/N "Show Limit Detection selector" field in Analysis Service. The field 'Allow Manual input of LD' will only be available for selection (visible and selectable) if the previous Y/N field is checked.
If "Show Limit Detection Selector" is enabled and "Allow Manual Input of LD" is enabled too, then the behavior will not change: the analyst will be able to …
=> LIMS-1775 Allow to select LDL or UDL defaults in results with readonly mode

bika/lims/browser/arimports.py, docs/CHANGELOG.txt
The client sample ID gets into the client reference of the ARImportItem and the actual client reference doesn't get imported. The issue is fixed by modifying the assignments while importing the file.
`test_ARImport.robot` ran without failures:
```
Set up plone.testing.z2.Startup in 0.243 seconds.
Set up plone.app.testing.layers.PloneFixture in 7.661 seconds.
Set up bika.lims.testing.BikaTestLayer in 48.543 seconds.
Running:
1/1 (100.0%)[ WARN ] Keyword 'Capture Page Screenshot' could not be run on failure: WebDriverException: Message: u'no such session\n  (Driver …
```
=> LIMS-1634 AR Import fields not importing correctly

bika/lims/content/analysisservice.py
This prevents the anoying selection list in the edit view when more than 6 schematas.
=> Relocate ProtocolID and CommercialID fields from AS to default schemata

bika/lims/browser/analysisrequest/workflow.py, bika/lims/browser/calcs.py, bika/lims/browser/js/bika.lims.utils.calcs.js, bika/lims/browser/js/bika.lims.worksheet.js, bika/lims/content/analysis.py, bika/lims/utils/analysis.py, docs/CHANGELOG.txt
For DL results, the system must not calculate the uncertainty, but leave it empty.
```
$ bin/test -v -p -s bika.lims --suite-name='bika.lims.tests'
Set up plone.testing.z2.Startup in 0.151 seconds.
Set up plone.app.testing.layers.PloneFixture in 5.841 seconds.
Set up bika.lims.testing.BikaTestLayer in 43.733 seconds.
Set up bika.lims.testing.BikaTestingLayer:Functional in 0.000 seconds.
Running:
Ran 15 tests with 0 failures and 0 errors in 54.967 seconds.
Running bika.lims.testing.SimpleTestingLayer:Functional tests:
Tear down bika.lims.testing.BikaTestingLayer:Functional in 0.000 seconds.
Tear down bika.lims.testing.BikaTestLayer in 0.012 seconds. …
```
=> LIMS-1808 Uncertainty calculation on DL

bika/lims/content/product.py, bika/lims/content/productitem.py, bika/lims/controlpanel/bika_productitems.py, bika/lims/profiles/default/types/ProductItem.xml, bika/lims/tests/test_Product.robot, docs/CHANGELOG.txt
In addition, calendar widget in Product item is changed to Bika's DateTimeWidget to maintain consistency with other content.
Added robot test for Product Item in test_Product.robot itself:
```
bin/test -t test_Product.robot
Set up plone.testing.z2.Startup in 0.173 seconds.
Set up plone.app.testing.layers.PloneFixture in 5.921 seconds.
Set up bika.lims.testing.BikaTestLayer in 53.756 seconds.
Set up plone.app.robotframework.remote.RemoteLibraryBundle:RobotRemote in 0.010 seconds.
Running:
1/2 (50.0%)[ WARN ] Keyword 'Capture Page Screenshot' could not be run on …
```
=> LIMS-1879 References for product, category and supplier in Product item.

bika/lims/browser/supplier.py, bika/lims/browser/supplier.zcml
Clicking on a supplier in the breadcrumbs of Product view redirects to Products list instead of reference samples.
=> Overrode breadcrumbs in Product view

bika/lims/validators.py, docs/CHANGELOG.txt
https://jira.bikalabs.com/browse/LIMS-1887
A pdb trace example:
-> for item in aq_parent(instance).objectValues():
(Pdb) item
<Method at /Plone/methods/method-1>
(Pdb) hasattr(item, 'UID') and item.UID() != instance.UID() and fieldname in item.Schema() and item.Schema()[fieldname].get(item) == value
False
(Pdb) value
'1212'
(Pdb) item.Schema()[fieldname].get(it)
1212
(Pdb) type(value) == type(it.Schema()[fieldname].get(it))
False
(Pdb) type(it.Schema()[fieldname].get(it))
<type 'int'>
=> LIMS-1887 uniquefield validator doesn't work properly

bika/lims/browser/analyses.py, bika/lims/browser/analysisrequest/add.py, bika/lims/browser/analysisrequest/manage_analyses.py, bika/lims/browser/batch/batchbook.py, bika/lims/browser/log.py, bika/lims/browser/referencesample.py, bika/lims/browser/sample.py, bika/lims/browser/widgets/analysisprofileanalyseswidget.py, bika/lims/browser/widgets/analysisspecificationwidget.py, bika/lims/browser/widgets/artemplateanalyseswidget.py, bika/lims/browser/widgets/referenceresultswidget.py, bika/lims/browser/widgets/serviceswidget.py, bika/lims/browser/widgets/srtemplateartemplateswidget.py, bika/lims/browser/worksheet.py, bika/lims/controlpanel/bika_analysisservices.py
Using pagesize=0 was a shortcut to hide the batching/pagination controls but in Plone > 4.3.4 causes this error in lists with 0 items.
Now using '999999' for the pagesize of these listings.
=> Fix LIMS-1930: AssertionError: Having an orphan size, higher than batch size is undefined

bika/lims/browser/order/configure.zcml, bika/lims/browser/order/order.py, bika/lims/browser/order/templates/order_view.pt, bika/lims/content/productitem.py, bika/lims/content/storagelevel.py, bika/lims/controlpanel/bika_productitems.py, bika/lims/controlpanel/bika_storagelevels.py, bika/lims/controlpanel/templates/storagelevels.pt, bika/lims/interfaces/__init__.py, bika/lims/monkey/contentmenu.py, bika/lims/setuphandlers.py, bika/lims/tests/test_InventoryOrder.robot
After an order is received, each row in the products list provides two input boxes. One takes the number of items and other takes the storage level to store in.
Storage level can be selected using a fuzzy finder, which displays assignable storage levels with their hierarchy (eg. Freezer>Drawer-1>Shelf-1) and the number of available spaces in them.
On storing the products, IDs of product items are assigned to the occupied storage levels and vice versa. The number of products stored, shown in the order view, is updated accordingly.
Also, children cannot be added to a storage level which stores a product.
- Considering dormancy among availability criteria.
- Discarding a product item from storage.
test_InventoryOrder.robot :
```
$ bin/test -t InventoryOrder.robot
Running …
```
=> LIMS-1961 Product Storage

bika/lims/content/client.py, docs/CHANGELOG.txt
The code at git@github.com:bikalabs/bika-export-import.git fixes LIMS-1397 and other issues by generalising the import/export of setupdata.  However the code has yet to be tested and integrated into bika.lims.
During this import, the existing client accessor causes cataloging to fail.  This one is identical, but works.
=> LIMS-1397 During site import, Client Title accessor fails.

bika/lims/profiles/default/structure/.objects, docs/CHANGELOG.txt
For new installations; existing order of items in Plone site root will
not be changed
=> LIMS-1965: Modified default navtree order

bika/lims/profiles/default/types/AnalysisRequest.xml, bika/lims/tests/test_bika_setup_ShowPrices.py, docs/CHANGELOG.txt
campbell:~/Plone/zeocluster$ bin/test -m bika.lims -t test_bika_setup_ShowPrices
Running bika.lims.testing.BikaSimple:Functional tests:
Set up plone.testing.z2.Startup in 0.176 seconds.
Set up plone.app.testing.layers.PloneFixture in 6.096 seconds.
Set up bika.lims.testing.SimpleTestLayer in 10.151 seconds.
Set up bika.lims.testing.BikaSimple:Functional in 0.000 seconds.
Running:
Ran 1 tests with 0 failures and 0 errors in 3.700 seconds.
Tearing down left over layers:
Tear down bika.lims.testing.BikaSimple:Functional in 0.000 seconds.
Tear down bika.lims.testing.SimpleTestLayer in 0.008 seconds.
Tear down plone.app.testing.layers.PloneFixture in 0.059 seconds.
Tear down plone.testing.z2.Startup in 0.004 seconds.
Tear down …
=> LIMS-1987: AR Invoice tab should not be shown if pricing is toggled off

bika/lims/browser/js/bika.lims.analysisrequest.js, docs/CHANGELOG.txt
Refactored the URL-rewriting done when AR transitions are fired from Plone contentmenu workflow actions.
TODO This should be using content_status_modify!  modifying the href is silly.  All the WorkflowAction instances are a little redundant - this stuff should all be handled with workflow-before and workflow-after events (if possible)
=> LIMS-1523: Site Error when transitioning AR from 'Manage Analyses' or 'Log' tab

bika/lims/controlpanel/bika_analysisservices.py, docs/CHANGELOG.txt
Cannot reproduce, and cannot see relation to https://github.com/bikalabs/Bika-LIMS/pull/1511.
Any column who does not have a key/value pair specified in item[column_name] will cause this error; so I have placed these two entries in each AnalysisService item explicitly to prevent whatever condition was causing them to fail to be displayed.
The bika_listing code should not have allowed this to happen: if you can reproduce it please tell me if you know how; I'd like to understand what happened here.
=> LIMS-1969: AR Add error when "Categorise analysis services" is disabled

bika/lims/barcode.py, bika/lims/browser/js/bika.lims.utils.barcode.js, bika/lims/tests/test_barcode_entry.py
Recognises title and ID of objects in bika_catalog / bika_setup_catalog
If an AR is scanned:
If it's attached to a Batch: redirect to Batch/batchbook view
If EditResults permission is available: redirect to manage_results
else: redirect to AR view screen.
If a Sample is scanned:
If the sample has a single AR:  delegate to AR logic above.
If sample has multipel ARs: redirect to Sample view screen.
All other recognised objects: redirect to object view screen.
---------
campbell ~/Plone/zeocluster $ bin/test -m bika.lims -t barcode
Running bika.lims.testing.BikaSimple:Functional tests:
Set up plone.testing.z2.Startup in 0.180 seconds.
Set up plone.app.testing.layers.PloneFixture in 6.162 seconds.
Set up bika.lims.testing.SimpleTestLayer …
=> LIMS-2025: Re-enable missing barcode shortcuts

bika/lims/content/instrument.py, docs/CHANGELOG.txt
Fixes [LIMS-2038 Catch 22. Cannot capture calibration results for uncalibrated instrument. Missed something, still... help please](https://jira.bikalabs.com/browse/LIMS-2038)
Fixed earlier in 319: [ LIMS-1996: On new system with no instrument data it is difficult to get going. The warnings could be confusing](https://jira.bikalabs.com/browse/LIMS-1996), PR https://github.com/bikalabs/Bika-LIMS/pull/1611
=> Fix the method in charge of checking if instrument is valid

bika/lims/content/instrumentcalibration.py, bika/lims/content/instrumentcertification.py, bika/lims/content/instrumentvalidation.py, bika/lims/profiles/default/types/InstrumentValidation.xml
https://jira.bikalabs.com/browse/LIMS-1928
From IRC:
<lemoene> Initially i thought the i strument's Asset number should go into those fields
<lemoene> but it was tagged incorrectly as 'Asset number' while it actually referes to the Calibration's 'Task ID'
<lemoene> please thus ignore my initial request that the field needs to auto poulate with the instrument's asset number. roll that back plaes
<lemoene> and 2. Just modify the field's tag to read 'Task ID'
<lemoene> dis that make sense pau?
<pau> ok, we are talking about instrument certificate then
<pau> yes, i'll do a roll-back
<lemoene> 2 of those tabs has the same issue. checking...
<lemoene> 3: Add Calibration Certificate AND Add Instrument Calibration Add Instrument Validation. Titles might have changed since
<lemoene> 3: Add …
=> LIMS-1928 -> Roll-back

bika/lims/browser/js/bika.lims.analysisrequest.add_by_col.js
JIRA: https://jira.bikalabs.com/browse/LIMS-1970
For some strange happenings when updating from 318, jquery's "replaceWith()" function was removing all TR's from the html variable 'data'
=> LIMS-1970 Analyses from AR Add form not displayed properly

bika/lims/browser/analysisrequest/publish.py, bika/lims/browser/analysisrequest/templates/analysisrequest_publish.pt, bika/lims/browser/analysisrequest/templates/reports/Multi_AR_default.css, bika/lims/browser/analysisrequest/templates/reports/Multi_AR_default.pt, bika/lims/vocabularies/__init__.py, docs/CHANGELOG.txt
**Ticket**: https://jira.bikalabs.com/browse/LIMS-1832
Result templates with the prefix Multi will be treated as multi-ar reports. (i.e. `multi_my_gorgeous_report.pt`). Custom templates for multi-ar reports can be created following the same procedure as the single-ar reports:
https://github.com/bikalabs/Bika-LIMS/wiki/Creating-new-report-templates
The ARs are grouped automatically by client and only one report (with the ARs from that client included) per client is generated. The number of ARs to render per page is responsability of the template itself, see line 18 from the Bika's default multi-ar template:
https://github.com/xispa/Bika-LIMS/blob/feature/LIMS-1832-multiar-reports/bika/lims/browser/analysisrequest/templates/reports/Multi_AR_default.pt#L18
=> LIMS-1832 New Results Template, COA. Multiple ARs in columns

bika/lims/jsonapi/__init__.py, docs/CHANGELOG.txt
```
/Plone/@@API/read
Module plone.jsonapi.core.browser.api, line 64, in __call__
Module plone.jsonapi.core.browser.decorators, line 48, in decorator
Module simplejson, line 321, in dumps
Module simplejson.encoder, line 237, in encode
Module simplejson.encoder, line 311, in iterencode
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe2 in position 10: invalid continuation byte
```
=> LIMS-2116: JSONAPI throws an UnicodeDecodeError

bika/lims/subscribers/objectmodified.py, docs/CHANGELOG.txt
When trying to edit and save a calculation imported directly from the setupdata spreadsheet.
```
Module Products.CMFFormController.FSControllerPageTemplate, line 91, in __call__
Module Products.CMFFormController.BaseControllerPageTemplate, line 29, in _call
Module Products.CMFFormController.ControllerBase, line 232, in getNext
Module Products.CMFFormController.Actions.TraverseTo, line 38, in __call__
Module Products.CMFFormController.FSControllerPythonScript, line 105, in __call__
Module Products.CMFFormController.Script, …
```
=> LIMS-2115: Error rises when saving a Calculation

bika/lims/browser/analysisrequest/publish.py
Added the specs_dict to return specs informations of each analysis to report
Usage:
Added the var specs_dict returning specs informations of each analysis to report
Usage:
\<span tal:condition="analysis/specs_dict/rangecomment | nothing">
\<span tal:content="structure analysis/specs_dict/rangecomment | nothing">\</span>
\</span>
=> Return specs of each analysis to report

bika/lims/content/instrument.py, docs/CHANGELOG.txt
[JIRA](https://jira.bikalabs.com/browse/WINE-71)
I don't know why Xispa set "DataInterfaceOptions" and" DataInterface" as not visible [here](https://github.com/bikalabs/Bika-LIMS/commit/58ef0fa48f0c1755d7640961513754d20319fa91#diff-2fb6d23392fdd7c495dcccf7aec97f3fR100).
To use the Export system the user has to select the Export instrument interface he/she wants to use from the instrument edition page.
=> WINE-71 Instrument. BBK WS export to FIA fails

bika/lims/browser/analysisrequest/publish.py, bika/lims/browser/calcs.py, bika/lims/browser/worksheet/views/printview.py, bika/lims/content/analysis.py, docs/CHANGELOG.txt
Relates to https://github.com/bikalabs/Bika-LIMS/pull/1670
The AR-specific specs were not taken into account in the reports.
@henriquechehad , with this PR, the specifications are set correctly to `specs` dict key, so `specs_dict` key has been removed.
=> LIMS-2133 Once in a while, specs var is going empty in results reports

bika/lims/browser/bika_listing.py, docs/CHANGELOG.txt
Due to #1681. Sorting machinery improved.
```
2015-11-20 11:23:35 ERROR Zope.SiteErrorLog 1448015015.760.314244035684 http://localhost:8090/Plone/analysisrequests/base_view
Module bika.lims.browser.analysisrequest.analysisrequests, line 741, in __call__
Module bika.lims.browser.bika_listing, line 678, in __call__
Module bika.lims.browser.bika_listing, line 938, in contents_table
Module bika.lims.browser.bika_listing, line 1058, in __init__
NameError: global name 'psi' is not defined
```
=> LIMS-2148 unable to sort bikalistings

bika/lims/browser/js/bika.lims.analysisrequest.add_by_col.js
Required by https://github.com/bikalabs/bika.health/pull/180
Exposed the `filter_combogrid` publicly, accessible via:
```javascript
window.bika.lims.AnalysisRequestAddByCol.filter_combogrid(element, filterkey, filtervalue, querytype);
```
Although we'd expect that adding the `has_combogrid_widget` wouldn't have any effect, sometimes the referencewidgets don't work properly because of this: while the grid is displayed succesfully, the selected item is not grabbed into the field itself.
=> Expose filter_combogrid from AnalysisRequestAddByCol publicly

bika/lims/browser/analysisrequest/workflow.py, bika/lims/tests/test_AnalysisRequest_retract.py, docs/CHANGELOG.txt
[JIRA](https://jira.bikalabs.com/browse/LIMS-1989)
pau@mendel:~/dev/Espurna/bikalims/zinstance$ bin/test -v -p -s bika.lims --suite-name='bika.lims.tests' --test='test_retract_an_analysis_request'
Test-module import failures:
Module: bika.lims.tests.test_doctests
TypeError: Module bika.lims.tests.test_doctests does not define any tests
Module: bika.lims.tests.test_robot
TypeError: Module bika.lims.tests.test_robot does not define any tests
Set up plone.testing.z2.Startup in 0.149 seconds.
Set up plone.app.testing.layers.PloneFixture in 5.154 seconds.
Set up bika.lims.testing.BikaTestLayer in 46.336 seconds.
Set up …
=> LIMS-1989 Retracting a published AR fails if one or more ASs has been retracted before publishing

bika/lims/browser/analysisrequest/templates/reports/example_1.css, bika/lims/browser/analysisrequest/templates/reports/example_1.pt, bika/lims/browser/js/bika.lims.analysisrequest.publish.js, bika/lims/browser/js/bika.lims.common.js, bika/lims/browser/js/bika.lims.graphics.controlchart.js, bika/lims/browser/js/bika.lims.graphics.range.js, bika/lims/browser/js/bika.lims.loader.js, bika/lims/profiles/default/jsregistry.xml, docs/CHANGELOG.txt
Added js for generating result ranges graphs, as well as a new report example.
Adding something like the following in any view will generate the graph automatically:
```html
<div class="range-chart" data-specs="[15,10,20,10]"></div>
```
where the attribute ``data-specs`` is [result, min, max, %error]
The graph gets scaled automatically with the size of the div, so
```html
<div class="range-chart" data-specs="[15,10,20,10]" style="width:200px"></div>
```
will generate a 200px-width graph
=> LIMS-1774 Shiny graphs for result ranges

bika/lims/browser/js/bika.lims.worksheet.js
When I load worksheets after applying this PR to master, I notice that the Method and Instrument fields are already completed in the same way as they are when this code is invoked on first render.
@xispa please tell me if I'm not understanding something, or, if there are some cases where the fields must be set differently, so that I can understand what changes need to be made!
=> LIMS-2067 Prevent initial method/instrument query for each analysis

bika/lims/browser/js/bika.lims.bikalisting.js, bika/lims/tests/test_bika_listing_show_more.robot
XML parsing fails when XML is not valid, and it seems that the HTML returned by bika_listing is not always valid XML.  parseHTML is not implemented in the current jquery.
A simple $() works.
=> WINE-81: use standard jquery to parse rows for show_more button

bika/lims/browser/js/bika.lims.worksheet.js, docs/CHANGELOG.txt
Although an invalid instrument cannot be assigned to an out-of-date or invalid instrument, the user should be able to add a new QC into a worksheet and assign that qc analysis to an invalid instrument. If the result set for that QC analysis is within the valid range, the instrument should automatically be available again after submit.
=> LIMS-2167 Cannot assign a QC analysis to an invalid instrument

bika/lims/browser/js/bika.lims.worksheet.js, docs/CHANGELOG.txt
Restores https://github.com/bikalabs/bika.lims/pull/1714 (was lost due to a push of an obsolete master on 15/12/7)
=> LIMS-2167 Cannot assign a QC analysis to an invalid instrument (revisited)

bika/lims/content/labproduct.py
This value (Decimal('0.00')) is falsish, and boolean logic cannot be used.  It results in the price being set to int(0) which has no .quantize.
Tests not required: the setupdata import/export routines which are used for robot tests, will fail if this error is present.
=> Fix error when labproduct's price is zero

bika/lims/utils/__init__.py, bika/lims/utils/analysis.py, docs/CHANGELOG.txt
in results formatting and decimal point routines, use math.isnan to prevent errors
=> WINE-111: Do not attempt detailed formatting of 'nan' results

docs/INSTALL.rst
Updated the INSTALL.rst file with latest packages for Fedora.
It now shows the list of packages users can install using dnf (yum is deprecated).
=> Updated for Fedora 22+

bika/lims/subscribers/analysis.py, bika/lims/subscribers/configure.zcml
Reject, Duplicate, Reference analyses subclass Analysis, so are mistakenly subjected to this code when they are deleted.  IAnalysis is provided directly by the Analysis class, and so can't be removed with noLongerProvides().
I've added the alsoProvides(IRoutineAnalysis) into the creation subscriber.
=> Analysis creation/modification subscribers now apply only to IRoutineAnalysis

README.rst, bika/lims/exportimport/instruments/foss/winescan/__init__.py, docs/CHANGELOG.txt, setup.py
Fixed bug in `bika.lims.exportimport.instruments.foss.winescan.WinescanCSVParser`
The `self.currentheader` instance variable is declared with all lowercase inside of the constructor.
``` python
def __init__(self, csv):
InstrumentCSVResultsFileParser.__init__(self, csv)
self.currentheader = None
```
This is consistent throughout the class but with two exceptions.
Lines 26-29
``` python
if not resid:
self.err("No Sample ID found", numline=self.num_line)
self.currentHeader = None
return 0
```
and 
Lines 83-86
``` python
self._addRawResult(resid, outvals, True)
self.currentHeader = None
return 0
```
I could not find a reference to `self.currentHeader` (camelcase) in any of the parent classes so I assume this was not intended.
=> LIMS-2208 WinescanCSVParser class instance variable misspelling

README.rst, bika/lims/browser/analysisrequest/analysisrequests.py, docs/CHANGELOG.txt, setup.py
Fixes failed client starts caused by indentation in `bika.lims.browser.analysisrequest.analysisrequests.py` on Line 660 when using bika.lims source in develop mode.
=> LIMS-2207 bugfix indentation

bika/lims/browser/calcs.py, bika/lims/browser/js/bika.lims.utils.calcs.js, bika/lims/content/analysis.py, bika/lims/tests/test_calculations.py, bika/lims/tests/test_manualuncertainty.py, bika/lims/utils/__init__.py, bika/lims/utils/analysis.py, docs/CHANGELOG.txt
**Reviewed**
[JIRA](https://jira.bikalabs.com/browse/LIMS-1917)
```
soliva@soliva-laptop:~/dev/labsanmartin/zinstance$ bin/test -v -p -s bika.lims --suite-name='bika.lims.tests' --test='TestCalculations'
Test-module import failures:
Module: bika.lims.tests.test_doctests
TypeError: Module bika.lims.tests.test_doctests does not define any tests
Module: bika.lims.tests.test_robot
TypeError: Module bika.lims.tests.test_robot does not define any tests
Set up plone.testing.z2.Startup in 0.192 seconds.
Set up plone.app.testing.layers.PloneFixture in 6.600 seconds.
Set up bika.lims.testing.BikaTestLayer in 56.254 seconds.
Set up …
```
=> LIMS-1917 Inconsistencies related to significant digits in uncertainties

bika/lims/browser/analyses.py, bika/lims/browser/templates/bika_listing_table_items.pt, bika/lims/tests/test_manualuncertainty.py, bika/lims/utils/__init__.py, docs/CHANGELOG.txt
[JIRA](https://jira.bikalabs.com/browse/LIMS-2215)
pau@mendel:~/dev/labsanmartin/bikalims/bikalims/zinstance$ bin/test -v -p -s bika.lims --suite-name='bika.lims.tests' --test='test_format_decimal_mark'
Test-module import failures:
Module: bika.lims.tests.test_doctests
TypeError: Module bika.lims.tests.test_doctests does not define any tests
Module: bika.lims.tests.test_robot
TypeError: Module bika.lims.tests.test_robot does not define any tests
Set up plone.testing.z2.Startup in 0.191 seconds.
Set up plone.app.testing.layers.PloneFixture in 6.051 seconds.
Set up bika.lims.testing.BikaTestLayer in 45.228 seconds.
Set up …
=> LIMS-2215 Decimal mark not working

bika/lims/browser/calcs.py, docs/CHANGELOG.txt
There is a problem in manage_results for those analyses that have an specification that has "<Min" and ">Max" fields defined. As a reminder, those two fields are used to show "< min" or "> max" instead of the result itself in views and reports.
The result input is updated with '< [min_value]' instead of keeping the result typed by the user when it moves the cursor out of the field. So, the system will save the min value instead of the result typed by the user. Javascript is responsible of this behavior, but this "visual replacement" of the result should only happen in read-only mode, never in write-mode.
[LIMS-2218: Result is replaced by min or max specs when "<Min" or ">Max" fields are used](https://jira.bikalabs.com/browse/LIMS-2218)
**Resolution**
The removal of the piece of code in …
=> LIMS-2218 Result is replaced by min or max specs when "<Min" or ">Max" fields are used

bika/lims/browser/js/bika.lims.analysisrequest.add_by_col.js, docs/CHANGELOG.txt
Specifications selection in AR add form doesn't work properly.
In the Analysis Request creation form, the manual selection of the specification has no effect in the selected analyses. When a profile is not selected but a Sample Type (with an specifications associated) before expanding manually a category of the analyses, the specification is correctly set in Specification field, but has no effect in the analyses (well, since the categories are collapsed, the system cannot set the specifications to any of them). If the user expands a category of analyses and then selects a Sample Type, the Specification field is properly filled and the analyses are updated with the specifications accordingly.
In summary, there are two problems here:
1. The selection of an Specification alone has no effect …
=> LIMS-2217 Specifications are not set in analyses on Analysis Request creation

bika/lims/tests/test_hiddenanalyses.py
This fix is required because the resolution of _[LIMS-1627 Pricing per Analysis Profile](https://jira.bikalabs.com/browse/LIMS-1627)_ involved the substution of AR's `Profile` field to `Profiles` (see https://github.com/bikalabs/bika.lims/pull/1584). This change allowed multiple Profiles per AR. In fact, the key `Profile` is no longer valid since then and when creating an AR manually, `Profiles` key must be used instead.
The test was not updated when LIMS-1627 was pushed, so it was still using `Profile`.
```
bin/test -s bika.lims -t TestHiddenAnalyses
Set up plone.testing.z2.Startup in 0.300 seconds.
Set up plone.app.testing.layers.PloneFixture in 8.478 seconds.
Set up …
```
=> Fix TestHiddenAnalyses unit test

bika/lims/browser/analyses.py, bika/lims/browser/analysisrequest/publish.py, bika/lims/browser/templates/bika_listing_table_items.pt, bika/lims/content/analysis.py, bika/lims/tests/test_limitdetections.py, bika/lims/utils/__init__.py, docs/CHANGELOG.txt
Results formatted with scientific notations with exponents are not displayed correctly in manage results views. The HTML tags for superindexes `<sup></sup>` are not rendered, but escaped and displayed in raw mode. Need to add the structure wildcard in the DOM elements from bika_listing_item template where formatted_results values are placed.
Similar problem in results reports. We added cgi.encode earlier (see PR[#1774 LIMS-2216 Results below LDL are not displayed in reports](https://github.com/bikalabs/bika.lims/pull/1774)) in order to make Detection Limits (LDL and UDL) symbols ('>' and '<') visible, but we didn't take into account the Sci notation.
```
$ bin/test -m bika.lims --layer=bika.lims.testing.BikaTestingLayer:Functional
Running bika.lims.testing.BikaTestingLayer:Functional …
```
=> LIMS-2220 Raw display of exponential notations in results manage views

bika/lims/tests/test_LIMS-2221-decimalmark-scinot.py, bika/lims/utils/__init__.py, docs/CHANGELOG.txt
Removed stupid stuff inside formatDecimalMark. No need to check if value is numeric, cause numeric results expressed with SciNot will always fail the check. Funny to see how formatDecimalMark has evolved to a really dummy method. To be removed, definitely.
=> LIMS-2221 Decimal mark doesn't work in Sci Notation

bika/lims/browser/worksheet/views/folder.py, bika/lims/controlpanel/bika_sampletypes.py, docs/CHANGELOG.txt
Misspelings: "Perdiod" to "Period". "QC Samples(Analyses)" to "QC Samples (Analyses)" and "Routine Samples(Analyses)" to "Routine Samples (Analyses)". Transifex's repos will be updated with the next release (3.1.11).
=> LIMS-1809. Typos. Perdiod and missing spaces

bika/lims/content/worksheet.py, bika/lims/tests/test_LIMS-2001-duplicate-one-analysis.py, docs/CHANGELOG.txt
When adding a duplicate in a worksheet, only the first analysis of the selected slot/AR gets duplicated. The problem rised up because of #1485 
This PR fixes [LIMS-2001 Duplicate for one analysis only](https://jira.bikalabs.com/browse/LIMS-2001) and the wrongly solved [LIMS-1745 Retracted analyses in duplictes](https://jira.bikalabs.com/browse/LIMS-1745)
```
$ bin/test -s bika.lims -t Test_LIMS2001
Set up plone.testing.z2.Startup in 0.233 seconds.
Set up plone.app.testing.layers.PloneFixture in 7.010 seconds.
Set up bika.lims.testing.BikaTestLayer in 57.995 seconds.
Set up bika.lims.testing.BikaTestingLayer:Functional in 0.000 seconds.
Running:
Ran 1 tests with 0 failures …
```
=> LIMS-2001 Duplicates for one analysis only

bika/lims/browser/worksheet/templates/analyses_transposed_cell.pt, docs/CHANGELOG.txt
In worksheet's transposed layout, the result fields in read-only mode are not displayed correctly when the result is below the LDL, the result is above the UDL or when a SciNotation other than the first one is selected. Basically, the result is not rendered as "structure" in the template.
=> LIMS-2225 Formatted results not displayed properly in Worksheet's transposed layout

bika/lims/browser/analysisrequest/publish.py
Change report attachment file name to AR.
PDF attachments on published reports had a random temp file name rather than a meaningful name.  This changes the name to the analysis request id.
=> Change report attachment file name to AR

bika/lims/browser/js/bika.lims.analysisrequest.add_by_col.js, docs/CHANGELOG.txt
When bar codes are set to be printed at Sample Registration the bar code is not been printed.
Regression due to [LIMS-1539 Printable Worksheets. In both AR by row or column orientations](https://github.com/bikalabs/bika.lims/pull/1434), missed to apply changes in ar-add.js
=> HEALTH-569 Bar code printing not working on sample registration

bika/lims/subscribers/objectmodified.py
A couple of conditions I missed, which caused modification of Contacts to fail if no user was associated.
=> WINE-166: Don't attempt to modify member properties if contact has no Username

bika/lims/browser/js/bika.lims.analysisrequest.add_by_col.js, docs/CHANGELOG.txt
When you select an analysis' checkbox (in AR add view), it should place the '1' to the right, indicating that this analysis is against first partition of the sample. If you submit the form before the partition number is calculated (via ajax!) then the form fails:
```
Module bika.health.browser.analysisrequest.ajax, line 54, in _call_
Module bika.lims.browser.analysisrequest.add, line 461, in _call_
Module bika.lims.browser.analysisrequest.add, line 602, in create_analysisrequest
KeyError: 'Partitions'
```
=> LIMS-2252 Partitions not submitted when creating AR if the form is submitted before partitions are calculated

bika/lims/tests/test_AnalysisRequest_retract.py
As a general rule, better to not use try-except:pass, and if there is no other option (because is caused by an undiscovered Plone's bug), then at least add a logger.warn 'someting' before the pass. In any case, never use try-execpts in tests, cause one could think the test did not passed because an assert was violated instead of an unknown 3rd-party bug (test failed versus error).
=> Remove confusing try except in a test

bika/lims/jsonapi/update.py
Bika JSON API doesn't work properly when using an instance installed in a proxied server. The update function tries to traverse the url to an object, but the url comes with 'VirtualHostBase', 'VirtualHostRoot', etc., so the restrictedTraverse function throws an error.
=> Issue with restrictedTraverse

bika/lims/jsonapi/update.py
Failure in test update (bika.lims.jsonapi.update.Update)
Traceback (most recent call last):
File "/usr/lib/python2.7/unittest/case.py", line 327, in run
testMethod()
File "/usr/lib/python2.7/doctest.py", line 2201, in runTest
raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for bika.lims.jsonapi.update.Update.update
File "/home/travis/build/bikalabs/bika.lims/bika/lims/jsonapi/update.py", line 23, in update
=> Fix doctest failure in bika.lims.jsonapi.update

bika/lims/jsonapi/update.py
```
Failure in test update (bika.lims.jsonapi.update.Update)
Traceback (most recent call last):
File "/usr/lib/python2.7/unittest/case.py", line 327, in run
testMethod()
File "/usr/lib/python2.7/doctest.py", line 2201, in runTest
raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for bika.lims.jsonapi.update.Update.update
File "/home/travis/build/bikalabs/bika.lims/bika/lims/jsonapi/update.py", line 24, in update
```
=>  Fix doctest failure in bika.lims.jsonapi.update (3.2)

bika/lims/browser/analysisrequest/analysisrequests.py, bika/lims/browser/analysisrequest/templates/analysisrequests.pt, docs/CHANGELOG.txt, setup.py
1) In order to be customised by extension packages using z3c.jbot, templates must be direct attributes of the class (with ViewPageTemplateFile).
2) When adding ARs, we always want to allow the ar_count to be set in the ui.  I changed the formatting and added the control as an input for manual entry.
=> LIMS-2299: Add ui for editing ar_count in all analysisrequest lists.

bika/lims/exportimport/setupdata/__init__.py
This is quite a common issue when creating setupdata sheets - now, get_object allows the AnalysisService title to be a keyword or a title.
=> Setup-data importer: allow analysisservice title or keyword, interchangeably

bika/lims/browser/js/bika.lims.analysisrequest.add_by_col.js, docs/CHANGELOG.txt
Fixes LIMS-2319.  This is an old issue that I've fixed a few times now, without sending a PR.
=> LIMS-2319 AR Add: Deleting a selected CC Contact corrupts the UID of reference widgets.

bika/lims/content/samplepoint.py, bika/lims/content/sampletype.py
Somehow this happens quite often, during various import scripts.  I guess there could be a neater way to fix it, but this works.
=> Prevent adding None values when setting Sampletype/Samplepoint relation

bika/lims/browser/js/bika.lims.worksheet.js, docs/CHANGELOG.txt
The selector '#lab_analyses #item_data, #analyses_form #item_data' does not appear in AR manage_results tabs, and it's absence causes an error that stops JS processing in AR view/edit/manage_results forms.
@xispa I think the 'fix' I applied here may cause issues where this code is expected to work in AR context?
Please verify it!  Thanks.
=> An error in initializeInstrumentsAndMethods:

bika/lims/skins/bika/bika_widgets/recordswidget.js
Small issue, the _more button in recordswidgets was including UIDs in new rows.
=> Properly clear UID of new RecordsWidget rows

bika/lims/content/worksheet.py
This check used to be done by the DuplicateAnalysis' ComputedField.
relates to https://github.com/bikalabs/bika.lims/pull/1844
=> LIMS-2391: Still have one error with worksheet Duplicate IDs

bika/lims/browser/analysisrequest/add.py, bika/lims/browser/analysisrequest/analysisrequests.py, bika/lims/browser/reports/productivity_dailysamplesreceived.py, bika/lims/browser/sample/printform.py, bika/lims/browser/sample/view.py, bika/lims/browser/templates/stickers/Code_128_1x48mm.pt, bika/lims/browser/templates/stickers/Code_128_1x72mm.pt, bika/lims/browser/templates/stickers/Code_39_1x54mm.pt, bika/lims/browser/templates/stickers/Code_39_1x72mm.pt, bika/lims/browser/templates/stickers/Code_93_2dx38mm.pt, bika/lims/browser/templates/stickers/Code_93_2x38mm.pt, bika/lims/content/analysisrequest.py
Never assume that SamplingDate has a value, always check for None before using the field!
This is needed for client packages which hide and/or un-require the SamplingDate field.  in future SamplingDate will conditionally become unrequired/invisible in bika.lims too, this PR will be necessary at that time, also.
=> Code Fix: SamplingDate is not assumed to be present

bika/lims/exportimport/setupdata/__init__.py, bika/lims/utils/__init__.py
AR Templates with titles that are not strings end up with empty sortable title and Title fields in the bika_setup_catalog and subsequently are not present in the list of templates available during AR creation.
=> Lims 2436: ar templates do not fire on ar create when title is an integer

bika/lims/browser/fields/historyawarereferencefield.py
Fixes the annoying bug "AttributeError: uid_catalog" when running tests.
```
$ bin/test -v -p -s bika.lims --layer=bika.lims.testing.BikaTestingLayer:Functional
Set up plone.testing.z2.Startup in 0.241 seconds.
Set up plone.app.testing.layers.PloneFixture in 8.155 seconds.
Set up bika.lims.testing.BikaTestLayer in 1 minutes 4.331 seconds.
Set up bika.lims.testing.BikaTestingLayer:Functional in 0.000 seconds.
Running:
34/45 (75.6%)                                                                                
Ran 45 tests with 0 failures and 0 errors in 9 minutes 17.985 seconds.
Tearing down left over layers:
Tear down …
```
=> Fix test's "AttributeError: uid_catalog"

bika/lims/tests/base.py, bika/lims/tests/test_LIMS-2062-cancelled-ars-visible-in-lists.py
Some browser paths like ""?analysisrequests_review_state=cancelled" do not work because plone.protect protect them.
=> error with plone protect

bika/lims/browser/analyses.py, bika/lims/browser/analysisrequest/analysisrequests.py, bika/lims/browser/worksheet/workflow.py, bika/lims/content/analysis.py, bika/lims/content/analysisrequest.py, bika/lims/content/analysisservice.py, bika/lims/content/bikasetup.py, bika/lims/content/referenceanalysis.py, bika/lims/content/worksheet.py, bika/lims/permissions.py, bika/lims/permissions.zcml, bika/lims/setuphandlers.py, bika/lims/skins/bika/guard_verify_transition.py, docs/CHANGELOG.txt
Add an option inside Analysis Service's Edit view to allow the lab manager to disable/enable "self-approval" of results for this Analysis Service. Also, add the same option in Bika Setup, that will act as the default value for all Analysis Services: the option set at Analysis Service level will have priority over the option set in Bika Setup.
When this option is set to enabled, the user will be able to verify those analyses for which he/she has submitted result. For informative purposes, display an icon stating this violation (same user that submit the results, verifies them).
**Self-verify option in Bika Setup**
**Self-verify option in Analysis Service edit view**
**Self-verify option disabled (worksheet manage results)**
**Self-verify option enabled (worksheet manage results)**
=> Add option to allow labman to self-verify analysis results

bika/lims/browser/analyses.py, bika/lims/browser/bika_listing.py, bika/lims/content/analysis.py, bika/lims/content/analysisrequest.py, bika/lims/content/analysisservice.py, bika/lims/content/bikasetup.py, bika/lims/content/duplicateanalysis.py, bika/lims/content/referenceanalysis.py, bika/lims/content/worksheet.py, bika/lims/skins/bika/bika_listing.css.dtml, bika/lims/utils/analysisrequest.py, docs/CHANGELOG.txt
In the Analysis Service edit view, a selection list to set the number of verifications required will be displayed (by default, 'system default'). Add the same configuration parameter in Bika Setup. The option set in Analysis Services will have priority over the option set at Bika Setup.
When enabled (>1 verifications), the analysis will require the verification from at least two different labmanagers. For informative purposes, display an icon stating this “multi-verification” next to the result.
This functionality doesn't override #1864 , so both features could coexist at the same time for the same analysis, so the same user that entered the result will be able to do the double verification if both options are enabled for a given analysis.
**Option for multi-approval in Bika Setup** …
=> Allow multi-approval/multi-verification of results

bika/lims/browser/analyses.py
Use the analysis' number of required verifications instead of the service's. Otherwise, and if the service's setting is updated, the analyses list will not display the correct number of verifications pending for a given analysis.
=> Use the analysis' numberofrequiredverifications instead of service's

AUTHORS.txt, bika/lims/browser/contact.py, bika/lims/browser/templates/login_details.pt, bika/lims/content/contact.py, bika/lims/content/labcontact.py, bika/lims/skins/bika/logged_in.cpy, docs/CHANGELOG.txt
System Users can be assigned to a `Contact` or `LabContact`. The `login_form` allows now to *link* or *unlink* an existing User via a small search form or create a new user, which will be automatically linked to the (Lab)Contact.
If the `Contact` or `LabContact` is deactivated and has a linked User, the User cannot log into the system anymore and unlinking the user from the (Lab)Contact is disabled.
See: https://jira.bikalabs.com/browse/LIMS-2455
=> LIMS-2455: (Lab)Contact/User Linkage Behavior

bika/lims/browser/bika-frontpage.py, bika/lims/browser/templates/bika-frontpage.pt, bika/lims/browser/templates/dashboard.pt, bika/lims/content/bikasetup.py, docs/CHANGELOG.txt
This feature allows to set a custom landing page in Bika LIMS via the `bika_setup`:
If the user is **not** authenticated, he/she gets redirected either to the custom landing page or to the std. Bika front-page.
If the user **is** authenticated, he/she gets redirected by its' user roles if the "Use Dashboard as default front page" option is selected. If this option is not selected, the user is redirected either to the custom landing page or to the default Bika front-page.
Furthermore, if the user is authenticated, he/she can switch between the dashboard/front-page by a link, which is displayed in the upper right corner of the dashboard (only visible for authenticated users and if the dashboard option is checked).
This PR implements LIMS 2357 and extends the feature by the custom landing …
=> LIMS 2357: Custom Landing Page and Switch-Link between Front-Page and Dashboard

bika/lims/browser/analysisrequest/publish.py, bika/lims/browser/analysisrequest/templates/reports/Multi_AR_default.css, bika/lims/browser/analysisrequest/templates/reports/Multi_AR_default.pt, docs/CHANGELOG.txt
- AR result table is no longer a single diff; handles pagination much better.
- Flag accredited results with icon.
- Add results interpretation where available after each AR group.
- Cache rendered data between calls to prevent templates from duplicate access.
- Add certificate number which increments each time report is printed.
=> LIMS-2341: Cleanup and format default Multi-AR COA

bika/lims/browser/analysisrequest/publish.py
The current publishing method sends a report to the client with the AR id as the name of the PDF file, but the file sent to the lab manager has the random tempfile id.
=> Change PDF filename on email to managers

AUTHORS.txt, bika/lims/browser/analyses.py, bika/lims/browser/bika_listing.py, bika/lims/browser/js/bika.lims.bikasetup.js, bika/lims/config.py, bika/lims/content/analysis.py, bika/lims/content/bikasetup.py, bika/lims/tests/test_MultiVerificationTypes.py, bika/lims/upgrade/to320.py, docs/CHANGELOG.txt
At the moment, the multi-verification allows the LabManager to set the number of verifications for an analysis are needed before an analysis being transitioned to the 'verified' status. Nevertheless, the same user (with "verifier" privileges) can trigger all the verifications until the analysis get verified.
The system must allow the LabManager to set one of the three options below in analysis service and also in Bika Setup when multi-verification is enabled:
- The analysis can be verified multiple-times by the same verifier
- The analysis can be verified multiple-times by the same verifier, but not consecutively
- The analysis cannot be verified multiple-times by the same user
A selection list in Bika Setup must be added below the option "Allow multi-verification of results", with the …
=> Multi-verification of analyses, with different verification types

bika/lims/browser/js/bika.lims.rejection.js, docs/CHANGELOG.txt
On a virgin bika.lims installation, the samples view shows an infinite spinner if the rejection workflow was not activated in bika setup.
This PR checks the array of rejection reasons first before accessing it with an index.
See: https://jira.bikalabs.com/browse/LIMS-2558
=> LIMS-2558: Fix JavaScript Uncaught TypeError: Cannot read property 'checkbox' of undefined causes endless Spinner

bika/lims/browser/bika_listing.py
Regression introduced since last release, so I did not add this entry to changelog.
=> LIMS-2502: Stickers did not print when receiving from batch/analysisrequests

bika/lims/browser/client/views/samplepoints.py
https://jira.bikalabs.com/browse/LIMS-2500
There was Title and Description columns only
Added other columns Sample Types, Composite Y/N, Sampling frequency, Attachments (hyperlinked)
And using folderitem instead of folderitems
--
[1] https://github.com/bikalabs/bika.lims/wiki/Bika-LIMS-Developer-Guidelines
[2] https://www.python.org/dev/peps/pep-0008
=> LIMS-2500 - Columns to be added to Sample Point lists

bika/lims/browser/referencesample.py
-workflow = getToolByName(obj, 'portal_workflow') 
+workflow = getToolByName(obj, 'portal_workflow') 
--
=> Put back a line that I deleted on a merge

bika/lims/browser/bika_listing.py, bika/lims/browser/referencesample.py, bika/lims/browser/worksheet/configure.zcml, bika/lims/browser/worksheet/views/add_control.py, bika/lims/browser/worksheet/views/services.py
Analysis Categories sans any analyses on the WS should stay collapsed. It otherwise makes for way to much scrolling.
https://jira.bikalabs.com/browse/LIMS-2361
All the categories/services where expanded
Expand the categories/services that have selected values and collapse those that don't have a value
--
=> LIMS-2361 ws creation collapse empty analysis categories

bika/lims/browser/analysisrequest/add.py, bika/lims/controlpanel/bika_analysisservices.py
AR Create. Column count should start at 1, not 0
Also removed CommercialID and ProtocolID on the AR form
https://jira.bikalabs.com/browse/LIMS-2335
Column (title)count started at 0, not 1
CommercialID and ProtocolID was on the table
Column (title)count starts at 1, not 0
Removed CommercialID and ProtocolID on the table
--
=> LIMS-2335 Formatting the AR create table

bika/lims/content/analysisservice.py, bika/lims/tests/test_method_instrument_constraints.py
Each `AnalysisService` contains a `_Method` field, which get set by the JavaScript logic in `bika.lims.analysisservice.edit.js`. Therefore, the corresponding `getMethod` method was used to implement the same logic in Python as it is done currently in JavaScript.
Within the content class `AnalysisService`, the `getMethod()` method returned the value of the field `_Method` if the field `InstrumentEntryOfResults` was True. Otherwise it returned `None`, which resulted in this failing test:
```
Error in test test_RegularAnalyses (bika.lims.tests.test_method_instrument_constraints.Test_MethodInstrumentConstraints)
Traceback (most recent call last):
File "/usr/lib/python2.7/unittest/case.py", line 327, in run
testMethod()
File "/home/travis/build/bikalabs/bika.lims/bika/lims/tests/test_method_ins …
```
=> Fixed AS getMethod functionality for Multi-Method handling

bika/lims/content/instrument.py
This PR is part of LIMS-2321 and fixes the display view issue when Instruments have multiple methods assigned. For more details, see:
https://jira.bikalabs.com/browse/LIMS-2321
Instrument View fails when multiple methods are assigned:
Traceback:
```
Module bika.lims.content.instrument, line 1, in <module>
Module Products.Archetypes.browser.utils, line 27, in translate
Module Products.Archetypes.utils, line 568, in getValue
TypeError: DisplayList keys must be strings or ints, got <type 'Acquisition.ImplicitAcquisitionWrapper'>
```
This is because the used `PicklistWidget` is not capable to handle referenced objects in its view template.
The view template of Instruments show all assigned Methods as comma separated strings.
--
I confirm I have read the [Bika LIMS Developer Guidelines][1] and …
=> LIMS-2321: Fix instrument display view with multiple instruments assigned

bika/lims/browser/batchfolder.py, bika/lims/content/batch.py
To make BatchID field editable
https://jira.bikalabs.com/browse/LIMS-2065
The field BatchID on a batch was not editable and only the generated BatchID was shown on the        batches listing 
Make BatchID editable and show the value on the list else show the generated BatchID
--
=> Lims 2065 display lab batch

bika/lims/browser/js/bika.lims.worksheet.js, bika/lims/browser/worksheet/templates/add_analyses.pt
Automatically display filtered list of analyses when search fields are changed, while adding analyses to a worksheet.
Any search parameter requires clicking the "search" button before modifying the list
The search button remains visible for visual clarity, but should normally not require clicking when any element with class='auto-search-on-change' is modified.
--
=> Worksheet/add_analyses: When parameters are modified, automatically filter analyses

bika/lims/browser/worksheet/views/analysisrequests.py
https://jira.bikalabs.com/browse/LIMS-2505
Sorting was done alphabetically
Sorted by numbers
--
=> LIMS-2505 Positon was a type string changed to int for sorting

bika/lims/browser/analysisrequest/publish.py, bika/lims/browser/analysisrequest/templates/analysisrequest_publish.pt, bika/lims/browser/js/bika.lims.analysisrequest.publish.js, docs/CHANGELOG.txt
See https://github.com/bikalabs/bika.lims/issues/1971 for details.
Publication reports allow only portrait printing.
A new checkbox "landscape" allows to switch the dimensions for landscape printing.
--
=> #1971: Landscape Layout for Reports

bika/lims/browser/analysisrequest/templates/ar_add_by_col.pt, docs/CHANGELOG.txt
See https://github.com/bikalabs/bika.lims/issues/1975 for details
No row highlighting and nor borders for label column, which makes it hard to use on wide-screens.
Row highlighting and border lines make it easier for the user to add new ARs
--
=> CSS improvements for AR Add View

bika/lims/skins/bika/bika_widgets/referencewidget.pt, docs/CHANGELOG.txt
Please see https://github.com/bikalabs/bika.lims/issues/1981 for details
Note: The commit 	2aabdc3 contains only HTML formatting.
Closing `</span>` HTML tag was missing in `referencebrowserwidget.pt` 
Valid HTML in `referencebrowserwidget.pt`, so that the transifex script stops to complain
--
=> Transifex Error processing bika/lims/skins/bika/bika_widgets/referencewidget.pt

bika/lims/browser/analysisrequest/templates/analysisrequests.pt, bika/lims/browser/client/views/analysisrequests.py, bika/lims/locales/af/LC_MESSAGES/bika.po, bika/lims/locales/el/LC_MESSAGES/bika.po, bika/lims/locales/es/LC_MESSAGES/bika.po, bika/lims/locales/es_PE/LC_MESSAGES/bika.po, bika/lims/locales/fa/LC_MESSAGES/bika.po, bika/lims/locales/fr/LC_MESSAGES/bika.po, bika/lims/locales/hu/LC_MESSAGES/bika.po, bika/lims/locales/it/LC_MESSAGES/bika.po, bika/lims/locales/ro_RO/LC_MESSAGES/bika.po, bika/lims/locales/tr_TR/LC_MESSAGES/bika.po, bika/lims/locales/uk_UA/LC_MESSAGES/bika.po, bika/lims/locales/zh_TW/LC_MESSAGES/bika.po, docs/CHANGELOG.txt
See GitHub issue https://github.com/bikalabs/bika.lims/issues/1984 for details.
Context Action for AR Add view not translated
Translation works for the "Add" icon label and for the "ARs" label
--
=> Fix i18n for AR Add context action

bika/lims/browser/configure.zcml, docs/CHANGELOG.txt
See https://github.com/bikalabs/bika.lims/issues/1967 for details
Aggregatedanalyses link from dashboard resulted in a 404
Aggregatedanalyses View is displayed
--
=> Added missing Aggregatedanalyses view registration

bika/lims/browser/js/bika.lims.calculation.edit.js, bika/lims/content/analysis.py, bika/lims/content/calculation.py, bika/lims/docs/Calculations.rst, bika/lims/tests/test_textual_doctests.py, bika/lims/validators.py, docs/CHANGELOG.txt
See https://github.com/bikalabs/bika.lims/issues/1999 for details.
External library functions like `scipy.special.gammaincinv` could not be used in Calculation formulas.
The user can use external functions in calculation formulas (as long as the import is in the `sys.path` of the Bika LIMS server). This opens also the door for custom functions available in the `sys.path`.
--
=> Issue-1999: Allow Python imports in calculation formulas

bika/lims/content/batch.py
When creating a batch, the BatchID field was being auto filled by the temporary object ID (eg. "batch.2017-04-18.0689260719")
fixes:
https://jira.bikalabs.com/browse/LIMS-2632 (Created Batches do not use ID server)
also accomodates:
https://jira.bikalabs.com/browse/LIMS-2065 (WIP: Display Lab Batch ID on Batch view page)
--
=> Fixed BatchID getter

bika/lims/browser/js/bika.lims.analysisrequest.add_by_col.js
Fixed:
when pressing the >> button for the Sampler row, all the columns should be completed as for the others
https://jira.bikalabs.com/browse/LIMS-2633
--
=> fix ar copy button on dropdown/select

bika/lims/browser/js/bika.lims.analysisrequest.add_by_col.js
https://github.com/bikalabs/bika.lims/issues/1995
CC contacts not saving during AR creation
On saving of the form, the method set_state  sets CCContact value to an empty string
because the UID does not get set on the HTML(This happens for MutliValue on the ReferenceWidget)
CC contacts are saved on AR creation
The change made is only to use set_state if  there's a UID and  don't default value to an empty string
--
=> On the set_state variable we not setting the default value

bika/lims/content/analysisservice.py, bika/lims/controlpanel/bika_analysisservices.py, docs/CHANGELOG.txt
Please see Issue https://github.com/bikalabs/bika.lims/issues/2015 for details.
Copy AS functionality raises an error, because LDL and UDL values are passed in as floats, but the field accepts only strings.
Copy AS functionality is working like a charm
--
=> Issue #2015: Convert UDL/LDL values to string before copy

bika/lims/browser/css/instrument_import.css, bika/lims/exportimport/instruments/abaxis/vetscan/vs2_import.pt, bika/lims/exportimport/instruments/agilent/masshunter/quantitative_import.pt, bika/lims/exportimport/instruments/alere/pima/beads_import.pt, bika/lims/exportimport/instruments/alere/pima/cd4_import.pt, bika/lims/exportimport/instruments/beckmancoulter/access/model2_import.pt, bika/lims/exportimport/instruments/biodrop/ulite/ulite_import.pt, bika/lims/exportimport/instruments/eltra/cs/cs2000_import.pt, bika/lims/exportimport/instruments/foss/fiastar/fiastar_import.pt, bika/lims/exportimport/instruments/foss/winescan/auto_import.pt, bika/lims/exportimport/instruments/foss/winescan/ft120_import.pt, bika/lims/exportimport/instruments/generic/xml_import.pt, bika/lims/exportimport/instruments/horiba/jobinyvon/icp_import.pt, bika/lims/exportimport/instruments/instrument.pt, bika/lims/exportimport/instruments/lifetechnologies/qubit/qubit_import.pt, bika/lims/exportimport/instruments/nuclisens/easyq_import.pt, bika/lims/exportimport/instruments/panalytical/omnia/axios_xrf_import.pt, bika/lims/exportimport/instruments/rigaku/supermini/wxrf_import.pt, bika/lims/exportimport/instruments/rochecobas/taqman/model48_import.pt, bika/lims/exportimport/instruments/rochecobas/taqman/model96_import.pt, bika/lims/exportimport/instruments/scilvet/abc/plus_import.pt, bika/lims/exportimport/instruments/sealanalytical/aq2/aq2_import.pt, bika/lims/exportimport/instruments/sysmex/xs/i1000_import.pt, bika/lims/exportimport/instruments/sysmex/xs/i500_import.pt, bika/lims/exportimport/instruments/tescan/tima/tima_import.pt, bika/lims/exportimport/instruments/thermoscientific/arena/xt20_import.pt, bika/lims/exportimport/instruments/thermoscientific/gallery/Ts9861x_import.pt, bika/lims/exportimport/instruments/thermoscientific/multiskan/go_import.pt, bika/lims/profiles/default/cssregistry.xml
https://jira.bikalabs.com/browse/LIMS-1833
There was no spacing between elements
Spacing between elements and added a header: Instrument Calibration Import
--
=> Lims 1833 instrument import screen tidying

bika/lims/browser/js/bika.lims.analysisrequest.add_by_col.js
CCContacts-not-saving-during-AR-creation
https://github.com/bikalabs/bika.lims/issues/1995 and I couldn't reproduce the issues reported on https://jira.bikalabs.com/browse/LIMS-2638
Causes this bug https://jira.bikalabs.com/browse/LIMS-2638
I took out the changes that I have made previously and the contacts are still not saved
--
=> Reverting back from changes made on branch

bika/lims/browser/validation.py
Inline validation on some fields falsely errors in ar-add and some other
contexts.
https://jira.bikalabs.com/browse/LIMS-2636
When selecting sampletype (or any other proxied Sample field) in the AR-Add form, the inline validation pops up and claims that a field value is required.  This means the user needs to enter the value twice before they can continue
Inline validation is ignored for these fields as well as other ignored fields types.
--
=> LIMS-2636 Prevent inline validation in ProxyField

bika/lims/browser/js/bika.lims.analysisrequest.add_by_col.js
This quick fix solves both screenshots in:
https://jira.bikalabs.com/browse/LIMS-2639
and does not result in endless spinner when blank field is copied across.
--
=> LIMS-2639 HotFix

bika/lims/skins/bika/bika_widgets/artemplateanalyseswidget.js, docs/CHANGELOG.txt
Please see https://github.com/bikalabs/bika.lims/issues/2012 for details.
Selection of an Analysis Profile in an AR Template did **not** expand the Category and select the contained Analyses of the Analysis Profile.
Selection of an Analysis Profile in an AR Template expands the category and selects the Analysis according to the profile.
--
=> AR Template Analysis don't get applied if an Analysis Profile is selected

bika/lims/jsonapi/api.py
Fixed missing schema when trying to retrieve a field of the portal object
--
=> Fix: Portal object has no schema/fields

bika/lims/api.py, bika/lims/docs/API.rst, bika/lims/jsonapi/catalog.py
- Dropped support for multi-catalog searches in search function.
- Removed manual inactive filtering in search function.
- Added two more functions.
- Updated Doctest.
--
=> Bika API changes

bika/lims/browser/js/bika.lims.bikalisting.js, docs/CHANGELOG.txt
Inverted logic, so that it is not needed to use the JQuery fadeout()
Methods, as it seems that it causes race condition if the request
returns while the button is still fading out.
Please see https://github.com/bikalabs/bika.lims/issues/2010 for more details
"Show More" Button disappears after first click.
"Show More" Button re-appears until the last batch of items is rendered.
--
=> Issue-2010: Fixed 'Show More' Button disappearance after first click

bika/lims/browser/worksheet/views/folder.py
Chainging action text(Reassign) on the Worksheet Listing View to Reassign Analyst
https://jira.bikalabs.com/browse/LIMS-2642
Action text(Reassign) is on the Worksheet Listing View 
Reassign Analyst action text(transition) to be on the Worksheet Listing View 
--
=> LIMS-2642 - Changed Reassign to Reassign Analyst

bika/lims/browser/batch/batchbook.py, docs/CHANGELOG.txt
Please see https://github.com/bikalabs/bika.lims/issues/2063 for further details and screenshots
Batchbook View raised an Error
Batchbook View works
--
=> Issue-2063: Fixed Error in Batchbook View

bika/lims/browser/bika_listing.py
On IE bika_listing fails when stack is nginx, haproxy, plone. The cookie value is [None] and the code doesn't handle that, This PR traps the ValueError and allow the function to continue as if cookie data was empty. The display column config work as they do in chrome or ff. Note that this issue does no occur if Varnish is in the stack BUT the display column config has no affect which is https://jira.bikalabs.com/browse/BC-42
If haproxy and no varnish, bika_listing crashes on IE.
If haproxy and no varnish, bika_listing does not crash on IE.
--
[2]: …
=> Handle the case where cookie on request is None on IE

bika/lims/utils/analysisrequest.py
https://jira.bikalabs.com/browse/BC-58
When an AR is created with an ARTemplate with multiple partitions, only one sample partition is created.
When an AR is created with an ARTemplate with multiple partitions, multiple sample partitions are created.
--
=> Fixed multiple partition creation from ARTemple

bika/lims/browser/bika_listing.py, bika/lims/content/analysiscategory.py, bika/lims/controlpanel/bika_analysisservices.py, docs/CHANGELOG.txt
Please see https://github.com/bikalabs/bika.lims/issues/2065 for further details and screenshots
- Listings in Bika Setup were not listed alphabetically per default
- Custom sort key for analysis categories did not work for the value `0.0`
- Sort on `sortable_title` did not work
- Sort order in Bika Listings sort alphabetically per default
- Custom sort key for analysis categories work as described in the help text
- It is possible now to sort on `sortable_title`
--
=> Issue-2065: Sort order in Bika Setup Listings

bika/lims/content/laboratory.py, docs/CHANGELOG.txt
Please see https://github.com/bikalabs/bika.lims/issues/2095 for details and screenshots
Portlet renders an error message if the accreditation logo could not be accessed.
Porlet does not render if the accreditation logo could not be obtained.
--
=> Issue-2095: Declare getAccreditationBodyLogo public

bika/lims/browser/analysisrequest/publish.py, bika/lims/browser/analysisrequest/templates/reports/bydepartment.css, bika/lims/browser/analysisrequest/templates/reports/bydepartment.pt, bika/lims/browser/analysisrequest/templates/reports/default.css, bika/lims/browser/analysisrequest/templates/reports/default.pt, bika/lims/browser/analysisrequest/templates/reports/example_1.css, bika/lims/browser/analysisrequest/templates/reports/example_1.pt, bika/lims/browser/js/bika.lims.analysisrequest.publish.js, bika/lims/browser/js/coffee/bika.lims.analysisrequest.publish.coffee, bika/lims/browser/viewlets/templates/attachments.pt, bika/lims/utils/__init__.py, docs/CHANGELOG.txt
Please see https://github.com/bikalabs/bika.lims/issues/2098 for details and screenshots
Inline rendered attachments are not in PDF report. Also the width does not resize to the max width of the page in preview.
Inline images appear in PDF and the preview works correct.
--
=> Issue-2098: Inline rendered attachments are not displayed in rendered PDF

bika/lims/browser/bika_listing.py
Spurious errors in log file regarding cookie problems
Check for valid cookie values and only show cookie value error when value is invalid.
--
=> Cleaned up cookie value check in BikaListingView

bika/lims/browser/analysisrequest/invoice.py, bika/lims/content/analysisrequest.py, bika/lims/tests/test_BC-33-retracted-analyses-shouldnot-be-invoiced.py
https://jira.bikalabs.com/browse/BC-33
Retracted Analysis showing on the invoice
Retracted Analysis not showing on the invoice.
Please note this PR only covers 3 cases
1. AR created using a Profile with [Use Analysis Profile Price] option
2. AR created using a Profile without the [Use Analysis Profile Price] option
3. AR created without using a profile but using the Analyses Service
If we have missed a use case please advise. 
--
=> BC-33 Retracted Analysis should not be invoiced

bika/lims/exportimport/instruments/shimadzu/icpe/multitype.py, bika/lims/tests/files/icp output.txt, bika/lims/tests/test_InstrumentInterfaceShimadzuICPE9000Multitype.py
Bug that comes from https://jira.bikalabs.com/browse/BC-7 for instrument Shimadzu ICP-AES ICPE-9000
https://jira.bikalabs.com/browse/BC-62
Reading incorrect columns for data: Column A is AR and Column B is Analysis Service Keyword 
The correct columns should be: Column C is AR and Column G is Analysis Service Keyword
--
=> Bc 62 testing instrument

bika/lims/profiles/default/metadata.xml, bika/lims/upgrade/configure.zcml, bika/lims/upgrade/to340.py
Master already has code destined for release 3.4.0 (like the refactored ID Server) but the upgrade steps don't reflect this. So this is an attempt to get master into a 3.4.0 ready state.
--
=> Added simple upgrade step 340

bika/lims/browser/analysisrequest/publish.py, docs/CHANGELOG.txt
Please see https://github.com/bikalabs/bika.lims/issues/2128 for further details.
Infinite recursion if no Address details were found on the Client or Contact.
Rendering succeeds w/o Address Details.
--
=> Issue 2128: Fixed infinite recursion if now 

bika/lims/browser/analysisrequest/view.py, bika/lims/content/attachment.py, bika/lims/profiles/default/metadata.xml, bika/lims/upgrade/configure.zcml, bika/lims/upgrade/to330.py, docs/CHANGELOG.txt
Please see https://github.com/bikalabs/bika.lims/issues/2129 for any more details.
Attachment files get stored in the Data.fs.
Attachment files get stored in the Blobstorage
--
=> Issue-2129: Migrate Attachment files to blob

bika/lims/browser/analysisrequest/publish.py, bika/lims/config.py, bika/lims/profiles/default/workflows/bika_duplicateanalysis_workflow/definition.xml, bika/lims/upgrade/to340.py
https://jira.bikalabs.com/browse/BC-88
https://jira.bikalabs.com/browse/BC-84
BC-88: On Client preferences there isn't an to choose <Client Name> as subject of email
BC-84: Typo on WS button 
On Client preferences add <Client Name> as subject of email option
--
=> Bc subject of email

bika/lims/browser/worksheet/views/folder.py
https://jira.bikalabs.com/browse/BC-83
Worksheet Templates not listed for WS Create
On the Select template drop down show the Worksheet Templates
--
=> BC-83 Select Template dropdown now shows Worksheet templates

bika/lims/browser/analysisrequest/analysisrequests.py, bika/lims/content/bikasetup.py, bika/lims/docs/SamplingCOCSetupTab.rst, bika/lims/tests/test_textual_doctests.py
https://jira.bikalabs.com/browse/BC-61
https://github.com/bikalabs/bika.lims/issues/2094
Stickers tab in Bika Setup and Enable Sampling, Enable Sampling Scheduling
Display individual Sample Partitions,Default Sample Retention Period
Enable Sample Rejection, Sample Rejection email notification are on Analyses tab in Bika Setup
BC-61
Change Stickers tab to Sampling and COC and move Enable Sampling, Enable Sampling Scheduling
Display individual Sample Partitions,Default Sample Retention Period
Enable Sample Rejection, Sample Rejection email notification from  on Analyses tab to Sampling 
and COC tab and also add 2 news fields COC Attestation Statement and COC Footer under 
Sampling and COC tab
GITHUB issue 2094
Display list filters to correspond with Bika Setup
To be Sampled, Scheduled …
=> BC-61 Started with Sampling and COC Setup tab

bika/lims/browser/analysisrequest/add.py, docs/CHANGELOG.txt
If one changed the AR number format to not be left padded with zeros, after AR creation it does not go to the sticker preview page.
https://github.com/bikalabs/bika.lims/issues/2152
If one changed the AR number format to not be left padded with zeros, after AR creation it does not go to the sticker preview page.
If one changed the AR number format to not be left padded with zeros, after AR creation it DOES go to the sticker preview page.
--
=> Issue 2152 auto print sticker on receipt

bika/lims/idserver.py
RenameAfterCreation provided the ability to bypass the Bika ID generator but did not work
https://github.com/bikalabs/bika.lims/issues/2155
Providing the _bika_id field to plone.api.create does not bypass the Bika ID generator
Providing the _bika_id field to plone.api.create does bypass the Bika ID generator
--
=> Fixed bug in RenameAfterCreation to allow Bika ID server to be ignored

bika/lims/content/bikasetup.py
User request more text space for the Attestation field on bika_setup
https://jira.bikalabs.com/browse/BC-101
Field used StringWidget
Field uses a TextAreaWidget
--
=> Change Attestation field from String to TextArea

bika/lims/exportimport/load_setup_data.py
https://jira.bikalabs.com/browse/LIMS-2165
Fails when trying to load setup data from a file
Load the setup data
--
=> Fixed Loading of setup data from a file

bika/lims/content/arimport.py, docs/CHANGELOG.txt
https://github.com/bikalabs/bika.lims/issues/2162
Partitions were not created from AR Import using ID server
Add renameAfterCreation to partition creation in ARImport
--
=> Added renameAfterCreation to partition creation in ARImport

bika/lims/browser/analysisrequest/publish.py, docs/CHANGELOG.txt
Please see https://github.com/bikalabs/bika.lims/issues/2173 for further details
Multi AR publication fails
Multi AR publication renders again.
--
=> Use AR as the context to retrieve the view.

README.rst
Change links in readme to match https://github.com/bikalims/bika.lims
--
=> fixed github links in readme

bika/lims/workflow.py, docs/CHANGELOG.txt
Please see https://github.com/bikalabs/bika.lims/issues/1977 for further details and screenshots.
Selecting the action menu in the upper right corner of an AR to trigger the `verify` transition set only the status of the AR to `verified`.
Contained Analyses are also in the `verified` state.
--
=> Issue 1977: Workflow transition fails on catalog brains

bika/lims/browser/client/workflow.py, docs/CHANGELOG.txt
https://jira.bikalabs.com/browse/BC-74
On the AR listing when the Sample button(transition) is clicked, Sampler and Date Sampled columns 
show incorrect error message when they are hidden 
To show correct error message for Sampler and Date Sampled columns when they are hidden and 
the user is trying to Sample transition an AR
--
=> BC 74 Sample Workflow Broken

bika/lims/browser/analysisrequest/add2.py, docs/CHANGELOG.txt
Please see https://github.com/bikalims/bika.lims/issues/2184 for further details
Cloning an existing AR with many selected Analyses takes more than 2 mins if the site contains many AnalysesServices. 
Cloning ARs is possible in an acceptable time.
--
=> Issue-2184: AR cloning takes too long on instances with many ASs

bika/lims/browser/analysisrequest/add2.py, docs/CHANGELOG.txt
https://github.com/bikalabs/bika.lims/issues/2183
function ajax_recalculate_prices is called even though the option 
Include and display pricing information in BIka Setup, Accounting Tab is not selected 
Prices must not be recalculated if  the Include and display pricing information option is not 
selected
--
=> Issue-2183-Recalculate-Show-Prices

bika/lims/browser/js/bika.lims.analysisrequest.add.js, bika/lims/browser/js/coffee/bika.lims.analysisrequest.add.coffee
If an extension package has hidden fields from the AR-Add form, this can result in set_reference_field being called on missing fields.
AR Add form spinner appears when modifying some reference field (eg, the Sample Type field will cause this to happen if the DefaultContainerType field is hidden by an AT Schema Extender).  A message claiming that "existing_uids is not defined" appears in console.log, and the form cannot be submitted.
This little defensive check causes the function to return early if required field element is missing.
--
[2]: …
=> AR Add 2: Prevent attempts to set missing fields

bika/lims/content/analysisservice.py, docs/CHANGELOG.txt
Please see Issue https://github.com/bikalims/bika.lims/issues/2004 for further details.
If the exponential format precision is empty (`None`), the following traceback occured:
```
Module bika.lims.browser.analysisrequest.view, line 93, in __call__
Module bika.lims.browser.bika_listing, line 1058, in contents_table
Module bika.lims.browser.bika_listing, line 1237, in __init__
Module bika.lims.browser.analyses, line 621, in folderitems
Module bika.lims.content.analysis, line 992, in getFormattedResult
Module bika.lims.utils.analysis, line 300, in format_numeric_result
Module bika.lims.utils.analysis, line 91, in …
```
=> Issue-2004: Traceback when AS exponential format precision is None

bika/lims/api.py, bika/lims/browser/bika_listing.py, bika/lims/docs/API.rst, bika/lims/subscribers/configure.zcml, bika/lims/subscribers/on_transition.py, bika/lims/workflow.py, docs/CHANGELOG.txt
Part of Issue https://github.com/bikalims/bika.lims/issues/2178
The Bika listing `cache_key` did only calculate the `UID` and the `modified` values. Unfortunately a WF transition leave the modification date unchanged.
From Slack:
<hr/>
mikemets [16:01] 
Recently we introduced some caching on the bika_listing and today it bit us in the butt. The cache key contained the method, uid and modified date. Unfortunately plone doesn't seem to update the modified date after transitioning on object's workflow. So we added the state to the key.  This works but looking up the state is not quick so I thought of adding an AfterTransition subscriber that does update modified. Anyone got any other ideas?
<hr/>
The brain is passed into the `cache_key` function to calculate the `review_state` as well.
--
I …
=> Fixed Bika listing cache key to include the review_state

bika/lims/browser/analysisrequest/templates/ar_add2.pt
Minor UI change to allow to change the AR number in the AR Add form.
Note: it is done very simple with a complete page reload, but this would also happen if one navigates back.
--
=> Added AR number selector to AR Add form

bika/lims/browser/analysisrequest/workflow.py, bika/lims/content/bikasetup.py, bika/lims/skins/bika/form_tabbing.js, docs/CHANGELOG.txt
Please see https://github.com/bikalims/bika.lims/issues/2204 for additional information.
All Clients and Lab Managers were notified on AR retract.
Clients and Lab Managers get only notified if the setting is active in Bika Setup
--
=> Issue-2204: Conditional Email Notification on AR retract

bika/lims/browser/analysisrequest/add2.py, bika/lims/browser/analysisrequest/templates/ar_add2.pt, bika/lims/browser/js/bika.lims.analysisrequest.add.js, bika/lims/browser/js/coffee/bika.lims.analysisrequest.add.coffee, docs/CHANGELOG.txt
Please see https://github.com/bikalims/bika.lims/issues/2211 for details.
It is not possible to change the number of ARs in AR Add form
AR controls added to change the number of ARs in AR Add form
--
=> Issue-2211: Added controls to change the number of ARs in the AR Add form

bika/lims/browser/analysisrequest/templates/ar_add2.pt, bika/lims/browser/js/bika.lims.analysisrequest.add.js, bika/lims/browser/js/coffee/bika.lims.analysisrequest.add.coffee, docs/CHANGELOG.txt
See Issue https://github.com/bikalims/bika.lims/issues/2214 
AR Add Controls look weird.
AR Add controls properly styled.
Also the weird JS logic was removed.
--
=> Issue 2214: AR add controls

bika/lims/idserver.py, docs/CHANGELOG.txt
https://github.com/bikalabs/bika.lims/issues/2215
IDServer generates ids for content types objects only 
This allows us to gen ids for none content type objects like reports that aren't saved.
--
=> Add an extra param "portal_type=None" to generateUniqueId

bika/lims/api.py, bika/lims/docs/API.rst, bika/lims/idserver.py, docs/CHANGELOG.txt
Please see https://github.com/bikalims/bika.lims/issues/2230 for further details.
AR creation fails if the Sample Type contains characters which are illegal in IDs
AR creation works even for Sample Types with weird names
--
=> Issue-2230: ID Server: Normalize Sample Type

bika/lims/browser/analysisrequest/workflow.py, bika/lims/browser/bika_listing.py, docs/CHANGELOG.txt
Please see Issue https://github.com/bikalims/bika.lims/issues/2219 for datails.
Selected items in listing tables were processed in random order.
If a use selected ARs from the list and clicked the copy button, the ARs were listed in random order in the AR Add form (and of course created in this random order).
Selected items in listing views keep their order and copied ARs are processed in reversed order.
--
=> Issue-2219: Order of copied ARss

bika/lims/browser/fields/proxyfield.py, bika/lims/docs/AnalysisRequests.rst, docs/CHANGELOG.txt
Please see https://github.com/bikalabs/bika.lims/issues/2218 for details.
Modification dates were not updated when a value was set on a proxy field
Modification date is set on proxy and holder object.
--
=> Issue-2218: Update modification dates when setting a proxy field

bika/lims/browser/worksheet/views/folder.py
Use toggle_cols in cookie to limit construction of column data in worksheet folder
https://jira.bikalabs.com/browse/LIMS-2690
All column data is gathered and returned to worksheets listing view
Only gather default or cookie specified column data
--
=> Worksheets listing performance improvement

bika/lims/browser/bika_listing.py
This is the second PR to fix https://github.com/bikalims/bika.lims/issues/2218.
AR listing table does not update its view when an AR was updated
Row in AR listing updates the value.
--
=> Issue-2218: Use the object to create the cached listing item

bika/lims/config.py
https://github.com/bikalabs/bika.lims/issues/2239
Default is Attached to Report
Default to Render in Report
--
=> Changed default Report Option in Attachment viewlet to Render In Report

bika/lims/browser/worksheet/views/add_analyses.py, docs/CHANGELOG.txt
https://jira.bikalabs.com/browse/BC-147
On the WS Add Analyses view default sort is by Client
On the WS Add Analyses view default sort should be by Due Date
--
=> BC-147 On the WS Add Analyses View, sort by due date

bika/lims/api.py, bika/lims/browser/analysisrequest/add2.py, buildout.cfg, docs/CHANGELOG.txt, travis.cfg
https://github.com/bikalims/bika.lims/issues/2242
Sample Points and Analysisspecs of all clients are displayed after the sample type was set in AR Add.
Only client-local Sample Points and Analysisspecs are displayed after the sample type was set in AR Add.
--
=> Issue-2242: New AR Add Form: Local Samplepoints with the same Sampletype from other clients get displayed

bika/lims/browser/analysisrequest/add2.py, bika/lims/browser/js/bika.lims.analysisrequest.add.js, bika/lims/browser/js/coffee/bika.lims.analysisrequest.add.coffee, docs/CHANGELOG.txt
https://github.com/bikalims/bika.lims/issues/2244
Samples from all clients were displayed in the AR Add form
Only samples from the locals client is displayed in the selection
--
=> Issue 2244: New AR Add Form: Local Samplepoints with the same Sampletype from other clients get displayed

bika/lims/adapters/referencewidgetvocabulary.py, docs/CHANGELOG.txt
https://github.com/bikalims/bika.lims/issues/2241
UnicodeDecodeError occurs when the search value contains unicode characters when coming from the reference widget (e.g. clicking on the Sample Point field when the Sample Type is "Öl") 
Reference Widget returns the search results w/o errors
--
=> Issue-2241: New AR Add Form: Server Error when the Sample Type contains German Umlauts (unicode characters)

bika/lims/browser/analysisrequest/add2.py, bika/lims/browser/js/bika.lims.analysisrequest.add.js, bika/lims/browser/js/coffee/bika.lims.analysisrequest.add.coffee, docs/CHANGELOG.txt
https://github.com/bikalims/bika.lims/issues/2237
Prices were recalculated even if the prices were hidden by Bika setup.
Prices are only recalculated if the Prices setting in Bika is enabled.
--
=> Issue-2237 recalculate prices on demand

bika/lims/validators.py, docs/CHANGELOG.txt
Linked issue: https://github.com/bikalims/bika.lims/issues/2229
Content creation fails if braces are present in the Title
Content can be created with braces in the title
--
=> Issue-2229: Traceback if the title contains braces "()" on content creation

bika/lims/browser/analysisrequest/add2.py, docs/CHANGELOG.txt, setup.py
Linked issue: https://github.com/bikalims/bika.lims/issues/2258
Required reference fields are flagged as missing in the AR Add form, even if they have a value set.
Validation of required reference fields pass in AR Add if references are present
--
=> Issue-2258: New AR Add Form: Required reference fields are flagged as missing and the form does not proceed

bika/lims/browser/worksheet/views/add_analyses.py, docs/CHANGELOG.txt
Linked issue: https://github.com/bikalims/bika.lims/issues/2225
Clicking on "Show more" breaks the entire listing table
Clicking on "Show more" works
--
=> Issue-2225: Worksheet "Show More" Button in Listing View breaks the whole Layout 

bika/lims/browser/instrument.py, docs/CHANGELOG.txt
Linked issues:
- https://github.com/bikalims/bika.lims/issues/2263
- https://github.com/bikalims/bika.lims/issues/2264
- Calibration table breaks if the user clicks on the sorting header
- Calibration table has no paging controls and shows only 30 Items
Calibration listing table works as expected
--
=> Issue-2263/-2264: Bika Listing: Instrument Calibration Table fixes

bika/lims/browser/analysisrequest/manage_analyses.py, docs/CHANGELOG.txt
Linked issue: https://github.com/bikalims/bika.lims/issues/2268
- Unit is not displayed in the "Manage Analyses" view
- Unit column is displayed per default
--
=> Issue-2268: Show the Unit in Manage Analyses View

bika/lims/browser/header_table.py, docs/CHANGELOG.txt
Linked issue: https://github.com/bikalims/bika.lims/issues/2270
Traceback occurs when setting 2 or more CCContacts in AR Table Header and clicking "Save"
Values get stored accordingly
--
=> Issue-2270:Setting 2 or more CCContacts in AR view produces a Traceback on Save

bika/lims/numbergenerator.py, bika/lims/upgrade/to340.py
Re-running upgrade step 3.4.0 on a site that is version 3.4.0 and already has samples will damage the counters in the number generator 
Linked issue: https://github.com/bikalims/bika.lims/issues/2272
Increment existing counters unnecessarily
Leave counters alone.
--
=> Ensure no counters in the number generator before initialising id server

bika/lims/browser/analysisrequest/publish.py, docs/CHANGELOG.txt
This fixes an issue where no emails were sent to CC Contacts
if the primary contact has no publication preferences set.
Linked issue: https://github.com/bikalims/bika.lims/issues/2280
CC Contacts received _no_ email if the primary contact has _no_ publication preferences set.
CC Contacts receive email according to their own publication preferences.
--
=> Issue-2280: Fix publication preferences for CC Contacts

bika/lims/browser/analysisrequest/add2.py, docs/CHANGELOG.txt
Linked issue: https://github.com/bikalims/bika.lims/issues/2282
AR Add columns where only the Contact got set per default, require all fields
AR Add columns where only the Contact got set per default, are not required unless another required field got set.
--
=> Issue-2282: Don't require all ARs if only the contact is set

bika/lims/browser/analysisrequest/add2.py, docs/CHANGELOG.txt
Linked issue: https://github.com/bikalims/bika.lims/issues/2288
Missing Client and Profiles field if the source AR was rejected
All fields are copied even if the source AR was rejected (`-R02`, `-R03` etc.)
--
=> Issue-2288: Fixed AR Copy from rejected ARs has missing fields

bika/lims/browser/analysisrequest/add2.py
Linked issue: https://github.com/bikalims/bika.lims/issues/2288
Copy AR failed for regular ARs
Copy AR is functioning again for regular ARs
--
=> Post-Fixture for Issue-2288

bika/lims/docs/IDServer.rst, bika/lims/idserver.py
Bugfix
If you use {year} in the ID format of anything other than Sample you get a KeyError.
{year} can be used in IDs of any portal type.
--
=> Allow year in any portal type's ID format string

bika/lims/exportimport/instruments/resultsimport.py
On an instrument import number of results showed is not correctly
End of file reached successfully: 2 objects, 7 analyses, 98 results
Linked issue: https://github.com/bikalims/bika.lims/issues/
End of file reached successfully: 2 objects, 7 analyses, 98 results
End of file reached successfully: 2 objects, 7 analyses, 14 results
--
=> Number (getResultsTotalCount) of results not recording correctly

bika/lims/content/analysis.py, docs/CHANGELOG.txt
Linked issue: https://github.com/bikalims/bika.lims/issues/2299
Please note:
From the perspective on an Analysis, the attributes originating from an AS in a certain version never change, because even if the AS was changed afterwards, it would get a new version where the Analysis wouldn't have access to.
The Analysis Service was looked up on all AS based attributes, which has a bad impact on the performance
AS based attributes are stored locally to avoid any further Service lookups.
--
=> Issue-2299: Fix low performance on retrieving analysis data

bika/lims/exportimport/instruments/resultsimport.py, bika/lims/validators.py, docs/CHANGELOG.txt
Linked issue: https://github.com/bikalims/bika.lims/issues/2302
UnicodeDecodeError occurs when the Title contains unicode characters.
Title field is correctly validated
--
=> Issue-2302: Fix UnicodeDecodeError if title field validator

bika/lims/browser/templates/bika_listing_table_items.pt, bika/lims/setuphandlers.py, docs/CHANGELOG.txt
Linked issue: https://github.com/bikalims/bika.lims/issues/2304
TypeError occurs
Category get expanded
--
=> Fixed TypeError in Analysis Specification category expansion

bika/lims/browser/instrument.py, docs/CHANGELOG.txt
Linked issue: https://github.com/bikalims/bika.lims/issues/2308
Some objects were missed in listings and unnecessary loops were done in the folderitems method.
Even temporary objects like `instrumentcalibration.2016-07-20.7846173955` were shown
--
=> Issue-2308: Added contentsMethod methods to instrument listing views

bika/lims/browser/referencesample.py
Do not use localized dates for control chart as it breaks the controlchart.js datetime parser.
bika.lims.graphics.controlchart.js
// Convert values to floats
// "2014-02-19 03:11 PM"
x_data_parse = d3.time.format("%Y-%m-%d %I:%M %p").parse;
=> do not use localized date for chart js.

bika/lims/idserver.py
Linked issue: https://github.com/bikalims/bika.lims/issues/2310
This is a post-fixture for PR: https://github.com/bikalims/bika.lims/pull/2311.
If the Number Generator Storage was flushed, the code to figure out the starting point for the sequence returned 0 for non-configure content types like e.g. `Client`
The start of the sequence is calculated correctly
--
=> IDServer: Fixed default split length value

bika/lims/validators.py
Linked issue: https://github.com/bikalims/bika.lims/issues/2302
This is a post fixture for PR: https://github.com/bikalims/bika.lims/pull/2303
Cannot create a new Client, because the UniqueFieldValidator produces an `UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1: ordinal not in range(128)`
Unique field validation works
--
=> UniqueFieldValidator: Encode value to utf-8 before passing it to the catalog

bika/lims/browser/analysisrequest/add2.py, bika/lims/browser/js/bika.lims.analysisrequest.add.js, bika/lims/browser/js/coffee/bika.lims.analysisrequest.add.coffee, docs/CHANGELOG.txt
Linked issue: https://github.com/bikalims/bika.lims/issues/2316
No error message is shown in the AR Add Form
Error message is shown in the AR Add form if the AR couldn't be created
--
=> AR Add Form: Pass error messages to the frontend

bika/lims/browser/analysisrequest/add2.py, docs/CHANGELOG.txt
Linked issue: https://github.com/bikalims/bika.lims/issues/2317
AR Add form fails if an Analysis Category was disabled
AR Add does not show services in disabled Analysis Categories
--
=> AR Add: Skip Analyses in disabled categories

bika/lims/browser/analysisrequest/add2.py, docs/CHANGELOG.txt
Linked issue: https://github.com/bikalims/bika.lims/issues/2320
Copy of multiple ARs from /analysisrequests view raises a Traceback in the background
No Traceback in the background on copy from /analysisrequests view
--
=> Fixed missing Client information in AR Add form when coming from AR listing view

bika/lims/docs/IDServer.rst, bika/lims/idserver.py
Items in the bika_setup_catalog do not continue in sequence after flushing the number generator
Linked issue: https://github.com/bikalims/bika.lims/issues/2322
After a flush, BSC items get new IDs from 1 instead of the next in the sequence
All items continue in the sequence after ng_flush
--
=> NG flush breaks id server
