bikalims/bika.lims

- bika/lims/browser/clientfolder.py
http://sentry.bikalabs.com/bikalims/healthbikalabscom/group/5026/
Preventive improvements.
> HEALTH-203 KeyError: 'searchTerm'

- CHANGELOG.txt
- bika/lims/browser/js/bika.lims.analysisrequest.js
- bika/lims/exportimport/load_setup_data.py
- bika/lims/tests/keywords.txt
- bika/lims/tests/test_AnalysisRequestView.robot
- bika/lims/tests/test_permisions.robot
My test log:
Set up plone.testing.z2.Startup in 0.154 seconds.
Set up plone.app.testing.layers.PloneFixture in 4.997 seconds.
Set up bika.lims.testing.BikaTestLayer in 43.289 seconds.
Running:
1/1 (100.0%)The following test left new threads behind:
Test CCContacts dropdown filter by client (test_AnalysisRequestView.robot)
New thread(s): [<_DummyThread(Dummy-1, started daemon 140142271624960)>]
Ran 1 tests with 0 failures and 0 errors in 45.663 seconds.
> Issue/1527 CC Contact on AR view (edit) offers all contacts in system

- bika/lims/browser/viewlets.py
> Fix version checker to correctly respect cache key

- bika/lims/exportimport/import.pt
- bika/lims/exportimport/setupdata/__init__.py
A try catch and a warning. Waiting for sponsorship. The best solution could be to upload the xlsx file and the attached data with a tar/zip file.
> LIMS-1624 Import default test.xlsx fails

- CHANGELOG.txt
- bika/lims/browser/batch/samples.py
No test done, too small issue.
> LIMS-1636 Batch Sample View crash

- CHANGELOG.txt
- bika/lims/browser/analysisrequest/workflow.py
Added a previous feature in  CHANGELOG.txt.
> LIMS-1524 Invalidate email does not have variables populated

- CHANGELOG.txt
- bika/lims/browser/worksheetfolder.py
A better style in the coulumns as it is said in https://jira.bikalabs.com/browse/LIMS-1199
> Issue/1199 Worksheet totals in WS lists

- bika/lims/browser/js/bika.lims.analysisrequest.js
Fixes
```
015-01-27 11:49:34 ERROR Bika (http://localhost:8091/Plone/clients/client15-1/PL15-0006-R01): [bika.lims.loader] Unable to load AnalysisRequestViewView: document.referrer.split(...)[1] is undefined
getClientUID@http://localhost:8091/Plone/portal_javascripts/Sunburst%20Theme/++resource++bika.lims.js/bika.lims.analysisrequest.js:173:13
filter_CCContacts@http://localhost:8091/Plone/portal_javascripts/Sunburst%20Theme/++resource++bika.lims.js/bika.lims.analysisrequest.js:165:13
AnalysisRequestViewView/that.load@http://localhost:8091/Plone/portal_javascripts/Sunburst%20Theme/++resource++bika.lims.js/bika.lims.analysisrequest.js:106:9
window.bika.lims.loadControllers/<@http://localhost:8091/Plone/portal_javascripts/Sunburst%20Theme/++resource++bika.lims.js/bika.lims.loader.js:194:25 …
```
> Sporadic AnalysisRequestViewView.js errors

- bika/lims/browser/__init__.py
- bika/lims/browser/fields/__init__.py
- bika/lims/browser/fields/datetimefield.py
- bika/lims/browser/widgets/datetimewidget.py
- bika/lims/content/analysisrequest.py
- bika/lims/content/sample.py
- bika/lims/locales/rebuild_i18n.sh
- bika/lims/skins/bika/bika_widgets/datetimewidget.pt
Created some utils and a bika.lims DateTimeField which respects the i18n date settings from the *.po files.
> Lims 1266 1i8n date error

- CHANGELOG.txt
- bika/lims/__init__.py
- bika/lims/browser/clientfolder.py
- bika/lims/profiles/default/registry.xml
- bika/lims/skins/bika/bika_widgets/referencewidget.pt
- bika/lims/skins/bika/logged_in.cpy
- bika/lims/tests/test_Registry.robot
review only, still need to write tests
> Added option to select landing page for clients in configuration registry

- bika/lims/upgrade/to317.py
https://github.com/bikalabs/Bika-LIMS/pull/1438
> Upgrade step required for PR#1438

- bika/lims/browser/analysisrequest/__init__.py
- bika/lims/browser/analysisrequest/configure.zcml
- bika/lims/browser/analysisrequest/invoice.py
- bika/lims/content/analysisrequest.py
- bika/lims/content/invoicebatch.py
- bika/lims/profiles/default/types/AnalysisRequest.xml
It's a poor and simple fix of the issue, I think that there is a lot to improve the invoice and email delivery modules. Future.
> Invoice's creation object and invoice's email delivery

- bika/lims/browser/js/bika.lims.analysisrequest.add.js
- bika/lims/tests/test_AnalysisRequest.robot
- bika/lims/tests/test_arspecs.robot
- docs/CHANGELOG.txt
Maybe changing python code could be a better and cleaner solution, but on the other hand it could be a big trouble since I don't know which python code depends on the possible changed results...
> LIMS-1693 Error trying to save a new AR

- bika/lims/browser/analysisrequest/publish.py
- bika/lims/utils/__init__.py
Revisited, was not finally included in 3.1.7
> Make weasyprint to print AR images

- bika/lims/content/analysis.py
- bika/lims/utils/__init__.py
- docs/CHANGELOG.txt
> LIMS-1696 Decimal mark conversion is not working with "<0,002" results type

- docs/CHANGELOG.txt
https://github.com/bikalabs/Bika-LIMS/pull/1468
> Changelog - LIMS-1737

- bika/lims/content/analysisrequest.py
- docs/CHANGELOG.txt
> LIMS-1739 Error with results interpretation field of an AR lacking deparments

- bika/lims/browser/analyses.py
- docs/CHANGELOG.txt
> LIMS-1740 Error when trying to view any Sample

- bika/lims/browser/js/bika.lims.analysisrequest.add.js
- bika/lims/content/analysisservice.py
i have fixed the bug.  i have also tried it on my machine.  i contact remove link is working.  i have hyperlinked the remove icon to remove any cc contact the user wants.
> LIMS-1734 AR contact remove

- bika/lims/content/method.py
- bika/lims/interfaces/__init__.py
- bika/lims/validators.py
Some changes to allow veterinary and others add-ons to interact with bika LIMS methods
> Adaptions fot veterinary methods.

- bika/lims/browser/analysisprofile.zcml
- bika/lims/browser/analysisrequest/add.py
- bika/lims/browser/analysisrequest/manage_analyses.py
- bika/lims/browser/artemplate.zcml
- bika/lims/browser/bika_listing.py
- bika/lims/browser/clientfolder.py
- bika/lims/browser/configure.zcml
- bika/lims/browser/js/bika.lims.bikalisting.js
- bika/lims/browser/templates/bika_listing_table.pt
- bika/lims/browser/templates/bika_listing_table_items.pt
- bika/lims/browser/widgets/analysisprofileanalyseswidget.py
- bika/lims/browser/widgets/artemplateanalyseswidget.py
- bika/lims/content/analysisprofile.py
- bika/lims/content/artemplate.py
- bika/lims/controlpanel/bika_analysisservices.py
- bika/lims/interfaces/__init__.py
- bika/lims/tests/test_ajax_categories.robot
- docs/CHANGELOG.txt
Required before the PR for LIMS-1811 can be merged.
> Lims 1812 ajax categories

- bika/lims/browser/analysisrequest/publish.py
> LIMS-1507 redux

- bika/lims/exportimport/instruments/__init__.py
- bika/lims/exportimport/instruments/sealanalytical/aq2/__init__.py
- bika/lims/exportimport/instruments/sealanalytical/aq2/aq2.py
- bika/lims/exportimport/instruments/sealanalytical/aq2/aq2_import.pt
- bika/lims/exportimport/instruments/sealanalytical/aq2/samples/13-12-12 ENVASS BH REST ANIONS.csv
- bika/lims/exportimport/instruments/sealanalytical/aq2/samples/AQ2 15-03-10 BOG Smpls ANIONS.csv
- bika/lims/tests/files/AQ2.csv
- bika/lims/tests/test_InstrumentInterfaceSealAnalytics.robot
- docs/CHANGELOG.txt
pau@mendel:~/dev/Espurna/bikalims/zinstance$ bin/test -s bika.lims -t AQ2
Set up plone.testing.z2.Startup in 0.158 seconds.
Set up plone.app.testing.layers.PloneFixture in 4.942 seconds.
Set up bika.lims.testing.BikaTestLayer in 42.047 seconds.
Running:
Ran 1 tests with 0 failures and 0 errors in 27.505 seconds.
Tearing down left over layers:
Tear down bika.lims.testing.BikaTestingLayer:Robot in 0.000 seconds.
Tear down plone.testing.z2.ZServer in 3.669 seconds.
Tear down bika.lims.testing.BikaTestLayer in 0.018 seconds.
Tear down …
> LIMS-1806 Instrument Interface. AQ2. Seal Analytical

- bika/lims/browser/analysisrequest/templates/analysisrequest_results_interpretation.pt
- bika/lims/browser/analysisrequest/templates/reports/bydepartment.pt
- bika/lims/browser/analysisrequest/templates/reports/default.pt
- bika/lims/browser/templates/bika_listing_table_items.pt
- bika/lims/utils/__init__.py
and syntax errors (which only Windows - and I - care about)
> Windows peculiarities

- bika/lims/content/analysisservice.py
- bika/lims/exportimport/instruments/__init__.py
@xispa @rockfruit urgent to maintain the hotfix reliability
> Some fixes from the pull requests

- bika/lims/browser/analysisrequest/add.py
- bika/lims/browser/js/bika.lims.analysisrequest.add_by_col.js
- bika/lims/browser/templates/bika_listing_table_items.pt
- bika/lims/skins/bika/bika_widgets/referencewidget.js
- bika/lims/skins/bika/bika_widgets/referencewidget.pt
- bika/lims/tests/test_AnalysisRequest_add.robot
@xispa 
```
$ xvfb-run bin/robot src/bika.lims/bika/lims/tests/test_AnalysisRequest_add.robot 
==============================================================================
test AnalysisRequest add                                                      
==============================================================================
Test price calculation when Template is selected                      | PASS |
------------------------------------------------------------------------------
Test price calculation when Profile is selected                       | PASS |
------------------------------------------------------------------------------
Test price calculation when services are manually selected            | PASS |
------------------------------------------------------------------------- …
```
> AR Add fixes: repair after bad merge from develop

- bika/lims/content/analysisservice.py
After a thoroughly testing done by leo, the last issue regarding to DLs, I guess...
> Low LDL values (more digits after 0.0) the value is not saved correctly in the AS Edit view

- bika/lims/browser/js/bika.lims.analysisrequest.add.js
- bika/lims/browser/js/bika.lims.analysisrequest.add_by_col.js
Haven't done any change in the logic
> Tabs replacement by whitespaces

- bika/lims/__init__.py
- bika/lims/content/productitem.py
- bika/lims/controlpanel/bika_productitems.py
- bika/lims/controlpanel/configure.zcml
- bika/lims/interfaces/__init__.py
- bika/lims/permissions.py
- bika/lims/permissions.zcml
- bika/lims/profiles/default/controlpanel.xml
- bika/lims/profiles/default/cssregistry.xml
- bika/lims/profiles/default/factorytool.xml
- bika/lims/profiles/default/propertiestool.xml
- bika/lims/profiles/default/structure/bika_setup/.objects
- bika/lims/profiles/default/structure/bika_setup/.preserve
- bika/lims/profiles/default/structure/bika_setup/bika_productitems/.properties
- bika/lims/profiles/default/types.xml
- bika/lims/profiles/default/types/ProductItem.xml
- bika/lims/profiles/default/types/ProductItems.xml
- bika/lims/profiles/default/workflows.xml
- bika/lims/setuphandlers.py
Added productitem content type via ProductItem and ProductItems, under bika_setup.
> LIMS-1864 Product Item entity

- bika/lims/upgrade/to319.py
- docs/CHANGELOG.txt
https://jira.bikalabs.com/browse/LIMS-1869?filter=10501
> LIMS-1869 Not possible to create an Analysis Request

- bika/lims/browser/analysisrequest/templates/analysisrequest_publish.pt
- bika/lims/browser/analysisrequest/templates/reports/bydepartment.css
- bika/lims/browser/analysisrequest/templates/reports/default.css
- bika/lims/browser/analysisrequest/templates/reports/default.pt
- bika/lims/browser/js/bika.lims.analysisrequest.publish.js
User can set the margins (in mm) manually in the report preview. The margins will be applied accordingly in the pdf report.
> Add margins selector in report preview

- bika/lims/browser/analysisrequest/publish.py
- bika/lims/browser/analysisrequest/templates/reports/bydepartment.pt
- bika/lims/browser/analysisrequest/templates/reports/default.pt
- bika/lims/content/analysisrequest.py
> Report signature bug

- bika/lims/content/analysisservice.py
- bika/lims/controlpanel/bika_analysisservices.py
- docs/CHANGELOG.txt
https://jira.bikalabs.com/browse/HEALTH-279
> Feature/health 279 Analysis services view updates

- bika/lims/profiles/default/types/InstrumentCalibration.xml
- docs/CHANGELOG.txt
https://jira.bikalabs.com/browse/LIMS-1923
>  LIMS-1923 Typo InstrumentCalibration

- bika/lims/__init__.py
- bika/lims/configure.zcml
- bika/lims/content/bikasetup.py
- bika/lims/content/storagelevel.py
- bika/lims/content/storageunit.py
- bika/lims/controlpanel/bika_storagelevels.py
- bika/lims/controlpanel/bika_storageunits.py
- bika/lims/controlpanel/configure.zcml
- bika/lims/controlpanel/templates/storagelevels.pt
- bika/lims/interfaces/__init__.py
- bika/lims/permissions.py
- bika/lims/permissions.zcml
- bika/lims/profiles/default/controlpanel.xml
- bika/lims/profiles/default/factorytool.xml
- bika/lims/profiles/default/propertiestool.xml
- bika/lims/profiles/default/structure/bika_setup/.objects
- bika/lims/profiles/default/structure/bika_setup/.preserve
- bika/lims/profiles/default/structure/bika_setup/bika_storageunits/.properties
- bika/lims/profiles/default/types.xml
- bika/lims/profiles/default/types/StorageLevel.xml
- bika/lims/profiles/default/types/StorageLevels.xml
- bika/lims/profiles/default/types/StorageUnit.xml
- bika/lims/profiles/default/types/StorageUnits.xml
- bika/lims/profiles/default/workflows.xml
- bika/lims/setuphandlers.py
- bika/lims/skins/jbot/Products.Archetypes.skins.archetypes.widgets.string.pt
- bika/lims/tests/test_StorageUnit.robot
- setup.py
Test log for `test_StorageUnit.robot`:
```
$ bin/test -t StorageUnit
Set up plone.testing.z2.Startup in 0.156 seconds.
Set up plone.app.testing.layers.PloneFixture in 5.378 seconds.
Set up bika.lims.testing.BikaTestLayer in 53.217 seconds.
Set up plone.app.robotframework.remote.RemoteLibraryBundle:RobotRemote in 0.010 seconds.
Running:
1/1 (100.0%)[ WARN ] Keyword 'Capture Page Screenshot' could not be run on failure: WebDriverException: Message: u'no such session\n  (Driver info: chromedriver=2.15.322448 (52179c1b310fec1797c81ea9a20326839860b7d3),platform=Linux …
```
> LIMS-1910 Storage unit with heirarchical storage levels

- bika/lims/browser/instrument.py
- docs/CHANGELOG.txt
https://jira.bikalabs.com/browse/LIMS-1929
> LIMS-1929 Translation error on Instrument Document page

- bika/lims/exportimport/setupdata/__init__.py
With this improvement we'll be able to upload files without definig its extensions, if the files are pdf ro jpg.
> Loading files without extension

- bika/lims/exportimport/setupdata/__init__.py
Cleaning the console's log trace to be more readable.
The system continues the uploading process even if one client is wrong.
> Some setupdata improvements

- bika/lims/exportimport/setupdata/__init__.py
https://jira.bikalabs.com/browse/HEALTH-228
Regarding to instrument manuals. Now is possible to upload one document through instrument sheet.
> Setup data improvement

- bika/lims/browser/js/bika.lims.analysisservice.js
- docs/CHANGELOG.txt
https://jira.bikalabs.com/browse/HEALTH-287
> HEALTH 287 Hyperlink in Instrument messages

- bika/lims/content/analysis.py
@xispa I'm sure self and service are full instances here.
Remember the naming convention we discussed where the 'get' prefix was removed from all indexes? This is the search/replace I was busy with (some stragglers) when I found these :)
> Fixed some possible false positive conditions

- bika/lims/browser/invoice.py
- bika/lims/browser/templates/invoice_content.pt
- docs/CHANGELOG.txt
https://jira.bikalabs.com/browse/LIMS-1934
> LIMS-1934 Hyperlinks in invoices

- bika/lims/upgrade/to319.py
- docs/CHANGELOG.txt
https://jira.bikalabs.com/browse/LIMS-1956
I just forgot to get the full object from the brain.
> LIMS-1956 Error upgrading to 319

- bika/lims/browser/analysisrequest/add.py
- bika/lims/content/analysisrequest.py
- docs/CHANGELOG.txt
https://jira.bikalabs.com/browse/LIMS-1959
RequestID is required, but is not filled out by a person since is not visible in the form. It's automaticaly filled by the system in [Line508](https://github.com/Espurna/Bika-LIMS/blob/d5274cf15b0a585c24bf9a68f70d072579dd92f8/bika/lims/browser/analysisrequest/add.py#L508)
> LIMS-1959 Not possible to create an AR

- bika/lims/configure.zcml
- bika/lims/content/configure.zcml
- bika/lims/content/expiry_portlet.pt
- bika/lims/content/expiry_portlet.py
- bika/lims/interfaces/__init__.py
- bika/lims/profiles.zcml
- bika/lims/profiles/default/portlets.xml
- setup.py
A portlet to alert expiry of product-items which will expire within ~2 months time.
To check just add the Expiry Portlet under Manage Portlets and one can see the list of product-items which are going to expire within two months, along with their expiry date.
While adding the portlet one can specify the limit (default:5) of how many items should be shown in the list.
> LIMS-1841 Expiry alert for product item's cancellation

- bika/lims/browser/templates/bika_listing.pt
- docs/CHANGELOG.txt
Please note that only the following has changed in bika_listing.pt: https://github.com/bikalabs/Bika-LIMS/commit/2d342d47cfb03a8dc63952ae0625d0c9febc2ddd
The rest is formatting (tabs and whitespaces removal): https://github.com/bikalabs/Bika-LIMS/commit/c94d9c57af20d742355a285ddb029dd0710fd4c8
> LIMS-2005 Click on Validations tab of Instruments it give error

- bika/lims/browser/analysisrequest/add.py
- docs/CHANGELOG.txt
https://jira.bikalabs.com/browse/LIMS-2002
> LIMS-2002 Error creating Analysis Requests from batch.

- bika/lims/browser/samplinground/analysisrequests.py
- bika/lims/content/analysisrequest.py
- bika/lims/content/configure.zcml
- bika/lims/content/samplinground.py
- bika/lims/profiles/default/catalog.xml
- bika/lims/profiles/default/propertiestool.xml
- bika/lims/profiles/default/structure/.preserve
- bika/lims/upgrade/to319.py
- docs/CHANGELOG.txt
Before PR: https://github.com/bikalabs/Bika-LIMS/pull/1619
JIRA: https://jira.bikalabs.com/browse/LIMS-1561
bin/buildout and upgrade step required!
> LIMS-1561 Editing a Sampling Round

- bika/lims/__init__.py
- bika/lims/browser/js/bika.lims.analysisrequest.add_by_col.js
- bika/lims/browser/srtemplate/artemplates.py
- bika/lims/content/artemplate.py
- docs/CHANGELOG.txt
https://jira.bikalabs.com/browse/LIMS-1545
- Blocking filled SampleTypes fields in the ARAdds which comes from a SamplingRound
- Introducing the logic for composite selection in ARAdd when coming from a SamplingRound
- Composite field in ARTemplate
- Composite column in SRTemplate's ARtemplates listing view
> LIMS-1545 Add "Composite Y/N" checkbox on AR Template

- bika/lims/content/samplinground.py
- docs/CHANGELOG.txt
https://jira.bikalabs.com/browse/LIMS-1564
- After canceling a sampling rounds, all its analysis request should be canceled too.
> LIMS-1564 Cancelling a Sampling Round

- bika/lims/browser/js/bika.lims.samplingrounds.js
- docs/CHANGELOG.txt
https://jira.bikalabs.com/browse/LIMS-2020
> LIMS-2020 Add Sampling Round - Department not available for selection

- bika/lims/browser/samplinground/add.py
- bika/lims/browser/samplinground/configure.zcml
- bika/lims/browser/samplinground/edit.py
- bika/lims/content/samplinground.py
- bika/lims/permissions.py
- bika/lims/permissions.zcml
- bika/lims/profiles/default/types/SamplingRound.xml
- bika/lims/profiles/default/workflow_csv/bika_samplinground_workflow.csv
- docs/CHANGELOG.txt
https://jira.bikalabs.com/browse/LIMS-1549
- Add and edit permissions added.
In my opinion checking the client's permissions in the views is the best approach. I can attach the specific client permission to the client's contact, but it becomes complicated to maintain when someone creates a new contact after.
> LIMS-1549 Sampling Round Templates privileges and permissions

- bika/lims/content/samplepoint.py
- bika/lims/profiles/default/types/SamplePoint.xml
- docs/CHANGELOG.txt
https://jira.bikalabs.com/browse/LIMS-1544
> LIMS-1544 Add "File attachment" field on Sample Point

- bika/lims/browser/analysisrequest/workflow.py
- bika/lims/browser/sample.py
- bika/lims/browser/samplinground/analysisrequests.py
- bika/lims/content/container.py
- docs/CHANGELOG.txt
https://jira.bikalabs.com/browse/LIMS-1543?filter=10700
> LIMS-1543 Add "Security Seal Intact Y/N" checkbox for partition container

- bika/lims/upgrade/to319.py
- docs/CHANGELOG.txt
https://jira.bikalabs.com/browse/LIMS-1908
> LIMS-1908 Navigation tree order

- bika/lims/upgrade/to319.py
- docs/CHANGELOG.txt
We'll curate in 319. 
curate/319 not needed any more
> All to 319

- bika/lims/browser/templates/bika_listing_table_items.pt
- bika/lims/browser/widgets/configure.zcml
- bika/lims/browser/widgets/referenceresultswidget.py
https://jira.bikalabs.com/browse/LIMS-1977
> LIMS-1977 Analysis categories don't expand

- bika/lims/upgrade/to319.py
I forgot to add Departments and ARTemplates to portal_catalog
> Update step for sampling rounds improved

- README.rst
- bika/lims/browser/templates/instrument_qc_failures_viewlet.pt
- docs/CHANGELOG.txt
https://jira.bikalabs.com/browse/LIMS-1983
> LIMS-1983 Translation error in Instrument message

- bika/lims/browser/js/bika.lims.bikalisting.js
- bika/lims/browser/widgets/referenceresultswidget.py
https://jira.bikalabs.com/browse/LIMS-2049
> LIMS-2049 Displaying lists doesn't work as expected

- bika/lims/browser/supplier.zcml
- bika/lims/permissions.zcml
- docs/CHANGELOG.txt
https://jira.bikalabs.com/browse/LIMS-1875
> LIMS-1875 Able to deactivate instruments and reference samples without logging in

- bika/lims/browser/analysisrequest/__init__.py
- bika/lims/browser/js/bika.lims.analysisrequest.add.js
- bika/lims/content/batch.py
- docs/CHANGELOG.txt
…te samples
Correctly discover the Client from the Batch, and restrict listing to show only samples from this client.
> LIMS-1933: Secondary Sample selection in Client Batches

- bika/lims/browser/dashboard.py
- bika/lims/browser/templates/dashboard.pt
- docs/CHANGELOG.txt
Maybe this should go to develop, but I think is almost a cosmetic change and I think multi-bar charts in dashboard don't make sense.
> Dashboard. Stacked-bar charts instead of multi-bar charts

- bika/lims/browser/analysisrequest/publish.py
- bika/lims/browser/analysisrequest/templates/analysisrequest_publish.pt
- bika/lims/browser/analysisrequest/templates/reports/Multi_AR_default.pt
- Detect multi-ar report when the template is from an extension
- Select the default template on page load
- Publish (generate the pdf and so on) was not working
> Small fixes regarding to Multi-AR publish

- bika/lims/browser/analysisrequest/add.py
- bika/lims/browser/analysisrequest/templates/ar_add.pt
- bika/lims/browser/analysisrequest/templates/ar_add_by_col.pt
- bika/lims/tests/test_bika_setup_ShowPrices.py
- docs/CHANGELOG.txt
Ran 2 tests with 0 failures and 0 errors in 7.903 seconds.
> LIMS-2075: Fix ShowPrices setting in AR-Add form

- bika/lims/browser/analysisrequest/add.py
- bika/lims/browser/js/bika.lims.analysisrequest.add_by_col.js
- bika/lims/content/batch.py
The last fix.
1 tests with 0 failures and 0 errors in 47.314 seconds.
> LIMS-1993: Secondary AR form *_uid handling for references

- bika/lims/content/arimport.py
- bika/lims/tests/test_ARImport.py
- docs/CHANGELOG.txt
Ran 2 tests with 0 failures and 0 errors in 11.131 seconds.
> Fix LIMS-2080: Correctly interpret default values

- bika/lims/content/arimport.py
- bika/lims/tests/test_ARImport.py
- docs/CHANGELOG.txt
Silently ignore workflow exceptions; if the validate transition is not
available, there should be some message explaining why to the user.
> LIMS-2081: WorkflowException after editing invalid ARImport.

- bika/lims/browser/analysisrequest/analysisrequests.py
- bika/lims/browser/worksheet/views/folder.py
I guess the best situation is one where folderitems does not exist on subclasses.  If folderitems is required, may be it should contain only minimal code, to illustrate that this is not the normal place for setting up the listing variables.
> Factor some folderitems code into __call__

- bika/lims/content/arimport.py
- bika/lims/tests/test_ARImport.py
- docs/CHANGELOG.txt
Ran 3 tests with 0 failures and 0 errors in 13.979 seconds.
> Fix LIMS-2114: Correctly create analyses from Profiles in ARImports

- bika/lims/testing.py
- bika/lims/tests/test_InstrumentInterfaceHoribaJobinYvon.robot
Augment "RobotRemote" library with additional keywords
Get UID
Create Object
Create AR
Write AT field values
> LIMS-2042 test pass

- bika/lims/exportimport/instruments/foss/winescan/__init__.py
- bika/lims/exportimport/instruments/foss/winescan/samples/FossWSBika3.csv
- bika/lims/exportimport/instruments/foss/winescan/samples/FossWSBika3V15-0090.csv
- docs/CHANGELOG.txt
- Added a new header type acceptance
[JIRA](https://jira.bikalabs.com/browse/WINE-72)
> WINE-72 Instrument. BBK WineScan Auto Import fails

- bika/lims/exportimport/instruments/foss/fiastar/__init__.py
- bika/lims/exportimport/instruments/foss/fiastar/samples/JC15-0025.csv
- docs/CHANGELOG.txt
Waiting for lemoene's [answer!](https://jira.bikalabs.com/browse/WINE-58?focusedCommentId=17801&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-17801)
https://jira.bikalabs.com/browse/WINE-58
> WINE-58 Instrument. BBK FIAStar import fails

- bika/lims/exportimport/instruments/foss/winescan/ft120.py
- docs/CHANGELOG.txt
[JIRA](https://jira.bikalabs.com/browse/WINE-76)
I wanted to improve the interface because it is complicated to understand, but I cannot find out how the .csv works, why there is a calibration line every four lines? Which columns should be saved? 
I don't know/understand the utility of _extractrowbycalibration function. 
I know that I did it, but I can't remember how the .csv should be interpreted (Mental note: write clear comments!!!!)
> WINE-76 WineScan FT120 Import warnings incorrect?

- bika/lims/browser/analysisrequest/publish.py
- bika/lims/browser/analysisrequest/templates/reports/TAL_field_reference.css
- bika/lims/browser/analysisrequest/templates/reports/TAL_field_reference.pt
Generates a report that includes some instructions on how to create results reports as well as the TAL reference for the current AR
> Add Bika LIMS TAL report reference in reports preview

- bika/lims/browser/batch/analysisrequests.py
This code tested via LIMS-2076 and LIMS-2062 tests
> LIMS-2157 Cancelled ARs appear in AR listing inside Batches

- bika/lims/browser/worksheetfolder.py
- bika/lims/content/batch.py
- docs/CHANGELOG.txt
[JIRA](https://jira.bikalabs.com/browse/LIMS-2149)
I cannot reproduce the error, so I added a preventive solution
> LIMS-2149 Cannot access to a Worksheet

- bika/lims/browser/invoicefolder.py
- bika/lims/profiles/default/structure/invoices/.properties
- bika/lims/profiles/default/types/InvoiceFolder.xml
- docs/CHANGELOG.txt
[JIRA](https://jira.bikalabs.com/browse/LIMS-2143)
@rockfruit I don't know how to change the name in the navigation bar in a installed instance...
It works in a new bika site.
> LIMS-2143 Statements vs Invoices

- bika/lims/browser/calcs.py
- bika/lims/browser/js/bika.lims.utils.calcs.js
- bika/lims/content/analysis.py
- bika/lims/content/analysisservice.py
- bika/lims/content/referenceanalysis.py
- bika/lims/tests/test_manualuncertainty.py
- bika/lims/utils/analysis.py
- docs/CHANGELOG.txt
[JIRA](https://jira.bikalabs.com/browse/LIMS-1917)
> LIMS-1917 Inconsistencies related to significant digits in uncertainties

- bika/lims/browser/worksheetfolder.py
[JIRA](https://jira.bikalabs.com/browse/LIMS-2169)
> LIMS-2169 Cannot start instance

- bika/lims/interfaces/__init__.py
- bika/lims/profiles/default/actions.xml
- bika/lims/profiles/default/structure/.objects
- bika/lims/profiles/default/structure/.preserve
- bika/lims/profiles/default/structure/queries/.properties
- bika/lims/setuphandlers.py
was lost due to a push of an obsolete master on 15/12/7
> Remove existing query code: Lost in mistaken branch delete.

- bika/lims/profiles/default/propertiestool.xml
- bika/lims/profiles/default/workflows.xml
sorry master.  I fixed this earlier in the wrong place.
> Removed the last redundant query/queryfolder code

- bika/lims/browser/js/bika.lims.analysisrequest.add_by_col.js
- docs/CHANGELOG.txt
[JIRA](https://jira.bikalabs.com/browse/LIMS-2177)
> LIMS-2177 template_set error when no template has been selected

- bika/lims/browser/js/bika.lims.utils.calcs.js
- [JIRA](https://jira.bikalabs.com/browse/LIMS-2175)
- [previous pull request](https://github.com/bikalabs/bika.lims/pull/1741)
> LIMS-2175 correction

- bika/lims/config.py
- bika/lims/content/contact.py
- bika/lims/content/labcontact.py
- bika/lims/interfaces/__init__.py
- bika/lims/vocabularies/__init__.py
- bika/lims/vocabularies/configure.zcml
Related with [JIRA](https://jira.bikalabs.com/browse/HEALTH-356)
>  custom publication preffs

- bika/lims/browser/worksheet/views/folder.py
- docs/CHANGELOG.txt
(This is the only part of support/3.1.8 which is not currently included in master already)
> LIMS-2149: Missing analysis prevents access to worksheet

- bika/lims/browser/analysisrequest/workflow.py
check also for EditFieldResults permission or ars with field analysis only are broken.
> check permission for field result edit.

- bika/lims/browser/analysis.py
- bika/lims/browser/js/bika.lims.utils.calcs.js
[JIRA](https://jira.bikalabs.com/browse/LIMS-2194)
I couldn't reproduce the issue, but I wrote some preventive code. Also, I took the freedom to prevent the analysis preselection when the result box is empty.
> LIMS-2194 Error when submitting a result

- bika/lims/browser/analysisrequest/manage_analyses.py
- docs/CHANGELOG.txt
[JIRA](https://jira.bikalabs.com/browse/LIMS-2209)
> LIMS-2209 error in manage analyises

- bika/lims/browser/widgets/srtemplateartemplateswidget.py
- bika/lims/content/artemplate.py
- docs/CHANGELOG.txt
[JIRA](https://jira.bikalabs.com/browse/LIMS-2212)
> LIMS-2212 Sampling round- Sampling round templates show all system analysis request templates

- bika/lims/browser/batchfolder.py
Missing ":" on else statement.
> Bugfix batchfolder.py

- bika/lims/subscribers/objectmodified.py
When Contact is modified, the Plone member values for Fullname and Email address are modified to match it.
> WINE-166 sync member and contact details

- bika/lims/utils/analysisrequest.py
- docs/CHANGELOG.txt
[JIRA](https://jira.bikalabs.com/browse/LIMS-2261)
> LIMS-2261 Cannot create analysis request

- bika/lims/utils/analysisrequest.py
From @veroc comment here: https://github.com/bikalabs/bika.lims/pull/1811#issuecomment-229277826
> imho the docstring is still not matched...
```
:param analyses:
Analysis services list.  If specified, augments the values in
values['Analyses']. May consist of service objects, UIDs, or Keywords.
```
> now it takes analyses keyword or else values analsyses. it doesn't augment values analyses.
> Augment the list of analyses instead of using one list or another

- bika/lims/utils/analysisrequest.py
Removed surplus code and added documentation in ```_resolve_items_to_service_uids```
> Surplus code removal and doc

- bika/lims/browser/analysisrequest/add.py
- bika/lims/utils/analysisrequest.py
- bika/lims/utils/samplepartition.py
- docs/CHANGELOG.txt
[JIRA](https://jira.bikalabs.com/browse/LIMS-2266)
> Crating partitions through Add form, doesn't create partitions.

- bika/lims/browser/clientfolder.py
- docs/CHANGELOG.txt
Adds a filter by term input box at the top of the clients list.
https://jira.bikalabs.com/browse/LIMS-2298
> LIMS-2298 Add filter in Clients folder list

- bika/lims/exportimport/instruments/lachat/quickchem.py
- bika/lims/testing.py
- bika/lims/tests/test_InstrumentInterfaceLachatQuickChemFIA.robot
- docs/CHANGELOG.txt
Added complete robot test for exporter.
(cherry picked exporter code from 4ce5d32d5b97de8a31c37028af87e0cac6be3d18)
> LIMS-2324 WS export to the LaChat Quick Chem FIA

- bika/lims/browser/analysisrequest/analysisrequests.py
- bika/lims/browser/analysisrequest/publish.py
- bika/lims/browser/js/bika.lims.site.js
- bika/lims/browser/referencesample.py
- bika/lims/browser/sample/partitions.py
- bika/lims/browser/sample/view.py
- bika/lims/browser/samplinground/analysisrequests.py
- bika/lims/browser/supplier.py
- bika/lims/browser/worksheet/views/printview.py
- bika/lims/content/analysisrequest.py
- bika/lims/content/sample.py
- bika/lims/skins/bika/bika_widgets/datetimewidget.js
SamplingDate and DateSampled now use a jquery datetimepicker.
> LIMS-2346 Add the time to sampled dates

- bika/lims/browser/analysisrequest/workflow.py
Fix occasional error while saving partitions
> Fix error while saving partitions

- bika/lims/browser/dashboard.py
- bika/lims/browser/templates/dashboard.pt
- docs/CHANGELOG.txt
> Added Analyses section in the dashboard

- .gitignore
- bika/lims/content/analysisrequest.py
- bootstrap.py
- buildout.cfg
- setup.py
- travis.cfg
> Fix Travis CI Tests

- bika/lims/content/analysisrequest.py
(cherry picked from commit d687e6281c614edabec3532b34cd0bbb2f06ee23)
In my cleanup I did some small reorganising of a couple of big conditionals, and I got it wrong.
> Fix bad code from LIMS-2447 (PEP8 and cleanup)

- templates/update_translations.in
> change directory to locales after tx push/pull

- bika/lims/browser/templates/stickers_preview.pt
> Syntax: chameleon comment cannot close with --->

- bika/lims/content/analysisrequest.py
resultdate called in getLate function prior to having been declared.
> resultdate variable not declared before use

- bika/lims/skins/bika/bika_widgets/rejectionsetupwidget.js
- buildout.cfg
Prevent removing last item
Prevent JS from clashing with other _more buttons in other contexts
> HEALTH-351 small JS fixes to RejectionReasons widget

- .travis.yml
- bika/lims/tests/base.py
- bika/lims/tests/test_LIMS-2062-cancelled-ars-visible-in-lists.py
- travis.cfg
- Removed occurances of plone.protect.auto
- Manual chromedriver installation
- Removed version pinning of p.p. in  travis buildout config
> Fixed Travis-CI Build

- bika/lims/browser/bika_listing.py
- bika/lims/content/analysis.py
- bika/lims/content/analysisrequest.py
- bika/lims/content/referenceanalysis.py
- bika/lims/content/worksheet.py
Added multiverification to referenceanalises and worksheets too...
> Feature/ Multi verification by different verifiers 

- buildout.cfg
> Added ipzope part to Buidlout

- bika/lims/browser/analysisrequest/workflow.py
- bika/lims/browser/bika_listing.py
- bika/lims/browser/client/workflow.py
- bika/lims/browser/js/bika.lims.bikalisting.js
- bika/lims/browser/js/bika.lims.bikalistingfilterbar.js
- bika/lims/browser/js/bika.lims.loader.js
- bika/lims/browser/js/bika.lims.site.js
- bika/lims/browser/templates/bika_listing_filter_bar.pt
- bika/lims/browser/templates/bika_listing_table.pt
- bika/lims/profiles/default/jsregistry.xml
- bika/lims/skins/bika/bika_listing.css.dtml
- bika/lims/upgrade/to320.py
This is the skeleton of the functionality, a new PR will come with the bar itself (already created and tested in another repo) and the enable/disable button in bika_setup.
This PR should be accepted in order to avoid future merge conflicts, the next PR with the bar will not create any conflict if this PR is accepted before because takes advantage of the functions defined here.
Description from JIRA:
> 
> The user could use the filter to sort either the list of Analysis Requests or the list of “Samples with results”
> Functional description:
> A new functionality in bika listing should be added, this functionality consists on a filtering bar to allow the user filter the list by more than one field or rang of values.
> This filter bar should be located over the current filter buttons that …
> Filter Bar for lists

- bika/lims/content/instrumentcertification.py
- bika/lims/docs/Instruments.rst
- bika/lims/interfaces/__init__.py
- bika/lims/tests/test_textual_doctests.py
Added missing interface for Instrument Certifications
> Added missing Instrument Certification Interface

- .travis.yml
- bika/lims/browser/contact.py
- bika/lims/browser/templates/login_details.pt
- bika/lims/content/contact.py
- bika/lims/docs/ContactUser.rst
- bika/lims/tests/test_textual_doctests.py
- docs/CHANGELOG.txt
`plone.api.user.get_user()` didn't find users located in ldap.
> LIMS-2473: Fixed Link User to Contact: LDAP Users not found

- bika/lims/content/bikasetup.py
- bika/lims/skins/bika/portlet_department_filter.pt
- bika/lims/subscribers/configure.zcml
- bika/lims/subscribers/dep_cookie.py
- docs/CHANGELOG.txt
- Fixed and refactored Eventhandler
- Fixed and refactored Portlet
- Fixed missing Schemata for Bika Setup field
> LIMS-2597: Fix AttributeError: `bika_setup` on login on a new Plone site w/o bika.lims installed

- bika/lims/content/analysisrequest.py
Cherry picked changes from
https://github.com/naralabs/bika.lims/commit/bd765946cfd94082f653e2905d9719596841cdae\#diff-9d57b6da936ef609e76f1d66d7886474
> AR: Fixed undefined variable

- bika/lims/browser/referencesample.py
- bika/lims/skins/bika/bika_widgets/worksheettemplatelayoutwidget.pt
Hide inactive reference samples in worksheet template layout
ReferenceSampleAnalysesView.folderitem() has no return value
bare try:except causes #GraphData JSON value to be empty
> LIMS-2576: Reference Sample errors and inconsistencies

- bika/lims/browser/invoicebatch.py
- bika/lims/content/invoicebatch.py
Regression since 3.1: missing total values for invoices in statements CSV
> Lims 2510 statements fixes

- bika/lims/browser/clientfolder.py
https://jira.bikalabs.com/browse/LIMS-2362
--
[1] https://github.com/bikalabs/bika.lims/wiki/Bika-LIMS-Developer-Guidelines
[2] https://www.python.org/dev/peps/pep-0008
> Added clientid, bulk and member discount columns to clientfolder

- bika/lims/browser/worksheet/views/folder.py
https://jira.bikalabs.com/browse/LIMS-XXX
--
[1] https://github.com/bikalabs/bika.lims/wiki/Bika-LIMS-Developer-Guidelines
[2] https://www.python.org/dev/peps/pep-0008
> Showing Verified Worksheets under all

- bika/lims/api.py
- bika/lims/docs/API.rst
- bika/lims/tests/test_textual_doctests.py
The Bika LIMS API makes your live immediately more pleasant!
It provides _single_ functions for _single_ purposes, it is tested, it is mighty, it is GREAT!
Common tasks like getting a tool, searching the catalog, checking the workflow state etc., were always repeated, or non-efficient functions were used, e.g. `getToolByName`.
The API acts as a central interface for common tasks done in Bika LIMS and follows the principle of DRY (Don't Repeat Yourself).
This will make Bika LIMS perform better, supports more readable and easier maintainable code and it avoids errors by non-core developers.
Please read the Doctest in `bika.lims/docs/API.rst` for further details.
--
tested the PR thoroughly and coded it according …
> Bika LIMS API

- bika/lims/api.py
- bika/lims/docs/API.rst
- bika/lims/utils/__init__.py
Some small changes to bika.lims.api.  Commit log holds details.
--
> Some small API changes

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
Added an GitHub Issue template for `bika.lims` core related issues
--
> Added issue template

- setup.py
> Added SecureMailHost dependency

- buildout.cfg
Added code-analysis part to buildout:
https://github.com/plone/plone.recipe.codeanalysis
--
> Added code-analysis part to buildout

- buildout.cfg
- travis.cfg
Pinned Plone versions for Travis
--
> Pinned Plone Versions for Travis CI

- bika/lims/api.py
- bika/lims/browser/fields/__init__.py
- bika/lims/browser/fields/proxyfield.py
- bika/lims/content/analysisrequest.py
- bika/lims/docs/AnalysisRequests.rst
- bika/lims/interfaces/__init__.py
- bika/lims/tests/test_textual_doctests.py
- docs/CHANGELOG.txt
Please see https://github.com/bikalabs/bika.lims/issues/1992 for details.
- Data is duplicated on AR and Sample
- Setting some fields on Sample conducted to data inconsistency between AR and Sample
- Data is not duplicated between AR and Sample
- Setting the data on AR or Sample keeps the data always consistent
--
> Implemented Proxy Field to fix data duplication between ARs and Samples

- bika/lims/docs/Calculations.rst
> Fixed Travis: Sort correctly by id

- bika/lims/api.py
- bika/lims/browser/fields/aranalysesfield.py
- bika/lims/interfaces/__init__.py
- bika/lims/jsonapi/api.py
- bika/lims/jsonapi/catalog.py
- bika/lims/jsonapi/configure.zcml
- bika/lims/jsonapi/datamanagers.py
- bika/lims/jsonapi/dataproviders.py
- bika/lims/jsonapi/fieldmanagers.py
- bika/lims/jsonapi/interfaces.py
- JSON return value is now completely delegated to IDataManager/IFieldManager adapter to be customizable
- Support for Analyses Fields
- Support for plone.app.blob Fields
- Added missing interface to ARAnalysesField
- Improved support for single and multi valued Reference Fields
- Full support for Dexterity Objects
- Code Cleanup & Refactoring
Please see http://plonejsonapiroutes.readthedocs.io/en/latest to get started with the Bika LIMS v2 JSON API
--
> JSONAPI v2 Service Pack 2

- bika/lims/exportimport/instruments/foss/winescan/ft120.py
https://github.com/bikalabs/bika.lims/issues/2037
When importing with incorrectly formatted instrument file following error could occur because of variables defined inside try:except: block which fails silently:
Traceback (most recent call last):
File "/home/bika/bikalims/src/bika.lims/bika/lims/exportimport/instruments/foss/winescan/ft120.py", line 76, in Import
importer.process()
File "/home/bika/bikalims/src/bika.lims/bika/lims/exportimport/instruments/resultsimport.py", line 327, in process
self._parser.parse()
File "/home/bika/bikalims/src/bika.lims/bika/lims/exportimport/instruments/resultsimport.py", line 224, in parse
jump = self._parseline(line)
File "/home/bika/bikalims/src/bika.lims/bika/lims/exportimport/instruments/foss/winescan/ft120.py", line 110, in _parseline
return …
> GH #2037: Remove bare try:except: clauses in foxx ft120 importer

- bika/lims/jsonapi/api.py
- bika/lims/jsonapi/configure.zcml
- bika/lims/jsonapi/fieldmanagers.py
- Added support for object Workflows (`?workflow=yes`)
- Added missing Dexterity ZCML configurations
- Fixed wrong type in AT Relation Field Manager
--
> JSONAPI v2 Service Pack 3

- bika/lims/jsonapi/api.py
- bika/lims/jsonapi/configure.zcml
- bika/lims/jsonapi/fieldmanagers.py
- Fixed workflow_info if now state variable could be found
- Custom field manager for computed fields
--
> JSONAPI v2: Several bugfixes

- bika/lims/browser/js/bika.lims.bikalisting.js
- bika/lims/browser/js/coffee/bika.lims.bikalisting.coffee
- docs/CHANGELOG.txt
Please see https://github.com/bikalabs/bika.lims/issues/2089 for further details and screenshots
If the browser language is other than english, the "display columns" do not match the actual columns (green check-marks) and clicking on a column has no effect (NB: Only when the columns are translated in a language different than english).
Display column works as specified
--
> Issue-2089: Listing display columns not working in other languages

- README.rst
This PR adds some informative https://shields.io badges
--
> Added Bika Shields.io badges

- bika/lims/utils/__init__.py
See https://github.com/bikalabs/bika.lims/issues/2098 for details
WeasyPrint URL fetcher did not work for HTTPS
WeasyPrint URL fetcher works for HTTPS
--
> Issue-2098: Fixed WeasyPrint custom URL fetcher

- bika/lims/browser/client/workflow.py
https://github.com/bikalabs/bika.lims/issues/2122
PR https://github.com/bikalabs/bika.lims/pull/2123 was created with .po files
No .po files on this PR
--
> 2122 - Coming from mikejmets:bugfix/2122-Sample-Action-Shows-No-Error.

- bika/lims/content/clientdepartment.py
- bika/lims/content/contact.py
Cleaned up variable name and removed unused imports
https://github.com/bikalabs/bika.lims/issues/2138
--
> Cleaned up variable name and removed unused imports

- bika/lims/configure.zcml
- bika/lims/content/clientdepartment.py
- bika/lims/content/clienttype.py
- bika/lims/docs/ContactDepartmentField.rst
- bika/lims/idserver.py
- bika/lims/interfaces/__init__.py
- bika/lims/profiles/default/types/ClientDepartment.xml
- bika/lims/profiles/default/types/ClientDepartments.xml
- bika/lims/subscribers/catalogobject.py
- bika/lims/subscribers/configure.zcml
Please see https://github.com/bikalabs/bika.lims/issues/2137 for details
IDs were generated from title
IDs generated from ID Server
--
> Issue-2137: Fixed ID generation and test

- bika/lims/workflow.py
- buildout.cfg
- travis.cfg
> Catch plone api error

- bika/lims/browser/bika_listing.py
- bika/lims/content/analysis.py
https://github.com/bikalabs/bika.lims/issues/2178
AR/Listing views take too long to render.
AR/Listing views render in an acceptable time.
--
> Performance Tuning in AR/Listing Views

- bika/lims/api.py
- bika/lims/browser/bika_listing.py
- bika/lims/content/analysis.py
- bika/lims/docs/API.rst
- docs/CHANGELOG.txt
Please see https://github.com/bikalims/bika.lims/issues/2178 for further details
--
> Backporting issue 2178 to 3.2.1

- bika/lims/api.py
- bika/lims/browser/bika_listing.py
- bika/lims/docs/API.rst
- bika/lims/subscribers/configure.zcml
- bika/lims/subscribers/on_transition.py
- bika/lims/workflow.py
- docs/CHANGELOG.txt
Please see https://github.com/bikalims/bika.lims/issues/2197 for further details
--
> Backport: Issue-2197 Bika listing cache key

- bika/lims/api.py
- docs/CHANGELOG.txt
Please see https://github.com/bikalims/bika.lims/issues/2200 for further details.
--
> Issue-2200: Include absolute URL in Bika Listing cache key

- bika/lims/skins/bika/bika_widgets/referencewidget.js
- docs/CHANGELOG.txt
Please see https://github.com/bikalims/bika.lims/issues/2207 for additional information
Referencewidget not working for newer jQuery version
Referencewidget keeps functional
--
> Issue 2207: Invalid Referencewidget jQuery selector

- bika/lims/browser/bika_listing.py
- docs/CHANGELOG.txt
> Prepare 3.2.1rc2

- bika/lims/browser/fields/proxyfield.py
- bika/lims/jsonapi/v1/__init__.py
- bika/lims/jsonapi/v1/update.py
- buildout.cfg
- docs/CHANGELOG.txt
- travis.cfg
https://github.com/bikalabs/bika.lims/issues/2245
Asynchronous updates of AR proxy fields failed.
Asynchronous updates of AR proxy fields succeeds.
--
> Issue-2245: Handle proxy fields in API field updates

- .github/PULL_REQUEST_TEMPLATE.md
> Updated GitHub template

- bika/lims/browser/analysisrequest/add2.py
Linked issue: https://github.com/bikalims/bika.lims/issues/2288
Code failed on new AR Add
AR Add works
--
> Another Post-Fixture for Issue-2288 (3rd attempt)
